/*
 * This file is generated by jOOQ.
*/
package id.mit.chrono.server.model;


import id.mit.chrono.server.model.tables.Columnset;
import id.mit.chrono.server.model.tables.Crantenna;
import id.mit.chrono.server.model.tables.Crantennatype;
import id.mit.chrono.server.model.tables.Crappvar;
import id.mit.chrono.server.model.tables.Crbrand;
import id.mit.chrono.server.model.tables.Crcell;
import id.mit.chrono.server.model.tables.Crcellclass;
import id.mit.chrono.server.model.tables.Crcellclassgroup;
import id.mit.chrono.server.model.tables.Crcellcoverage;
import id.mit.chrono.server.model.tables.Crcellnodeid;
import id.mit.chrono.server.model.tables.Crcellpattern;
import id.mit.chrono.server.model.tables.Crcellstatus;
import id.mit.chrono.server.model.tables.Crcollectorstatus;
import id.mit.chrono.server.model.tables.Crcollectortask;
import id.mit.chrono.server.model.tables.Crcollectortaskfiles;
import id.mit.chrono.server.model.tables.Crcollectortasksources;
import id.mit.chrono.server.model.tables.Crcompany;
import id.mit.chrono.server.model.tables.Crcountry;
import id.mit.chrono.server.model.tables.Crdataexport;
import id.mit.chrono.server.model.tables.Crdataexporttask;
import id.mit.chrono.server.model.tables.Crdataexporttask2;
import id.mit.chrono.server.model.tables.Crdataexporttype;
import id.mit.chrono.server.model.tables.Crdatagroup;
import id.mit.chrono.server.model.tables.Crdatasource;
import id.mit.chrono.server.model.tables.Crdatasourcecommands;
import id.mit.chrono.server.model.tables.Crdatasourcetype;
import id.mit.chrono.server.model.tables.Crdatatype;
import id.mit.chrono.server.model.tables.Crenodebmme;
import id.mit.chrono.server.model.tables.Crfinalizertask;
import id.mit.chrono.server.model.tables.Crfinalizertask_20201023;
import id.mit.chrono.server.model.tables.Crflag;
import id.mit.chrono.server.model.tables.Crgeomap;
import id.mit.chrono.server.model.tables.Crgeomap2;
import id.mit.chrono.server.model.tables.Crgeomap3;
import id.mit.chrono.server.model.tables.Crisland;
import id.mit.chrono.server.model.tables.Crlandstatus;
import id.mit.chrono.server.model.tables.Crmapentity;
import id.mit.chrono.server.model.tables.Crmapfield;
import id.mit.chrono.server.model.tables.Crmaplevel;
import id.mit.chrono.server.model.tables.Crmapnptq;
import id.mit.chrono.server.model.tables.Crmapparser;
import id.mit.chrono.server.model.tables.Crnode;
import id.mit.chrono.server.model.tables.Crnodecalc;
import id.mit.chrono.server.model.tables.Crnodecategory;
import id.mit.chrono.server.model.tables.Crnodemaps;
import id.mit.chrono.server.model.tables.Crnodepattern;
import id.mit.chrono.server.model.tables.Crnodeplace;
import id.mit.chrono.server.model.tables.Crnodestate;
import id.mit.chrono.server.model.tables.Crnodestatus;
import id.mit.chrono.server.model.tables.Crnodetype;
import id.mit.chrono.server.model.tables.Crnptq;
import id.mit.chrono.server.model.tables.Crobject;
import id.mit.chrono.server.model.tables.Crobjectcategory;
import id.mit.chrono.server.model.tables.Crprocessorstatistic;
import id.mit.chrono.server.model.tables.Crprocessortaskfiles;
import id.mit.chrono.server.model.tables.Crprocessstatus;
import id.mit.chrono.server.model.tables.Crprovince;
import id.mit.chrono.server.model.tables.Crqueryset;
import id.mit.chrono.server.model.tables.Crranbts;
import id.mit.chrono.server.model.tables.Crrancell;
import id.mit.chrono.server.model.tables.Crrancelladv;
import id.mit.chrono.server.model.tables.Crrancontroller;
import id.mit.chrono.server.model.tables.Crrelsitesitearea;
import id.mit.chrono.server.model.tables.Crrevenueclass;
import id.mit.chrono.server.model.tables.Crsettings;
import id.mit.chrono.server.model.tables.Crsite;
import id.mit.chrono.server.model.tables.CrsiteOld;
import id.mit.chrono.server.model.tables.Crsitearea;
import id.mit.chrono.server.model.tables.CrsiteareaOld;
import id.mit.chrono.server.model.tables.Crsiteflags;
import id.mit.chrono.server.model.tables.Crsiteprefix;
import id.mit.chrono.server.model.tables.Crsitestate;
import id.mit.chrono.server.model.tables.Crsitetype;
import id.mit.chrono.server.model.tables.Crsourceparser;
import id.mit.chrono.server.model.tables.Crstaticgcell;
import id.mit.chrono.server.model.tables.CrstaticgcellCopy;
import id.mit.chrono.server.model.tables.Crstaticlcell;
import id.mit.chrono.server.model.tables.CrstaticlcellCopy;
import id.mit.chrono.server.model.tables.Crstaticucell;
import id.mit.chrono.server.model.tables.Crsubdistrict;
import id.mit.chrono.server.model.tables.Crsummaryarea;
import id.mit.chrono.server.model.tables.Crsummarynation;
import id.mit.chrono.server.model.tables.Crsummaryoss;
import id.mit.chrono.server.model.tables.Crsummaryregional;
import id.mit.chrono.server.model.tables.Crsummaryvendor;
import id.mit.chrono.server.model.tables.Crtest;
import id.mit.chrono.server.model.tables.Crtimecatalog;
import id.mit.chrono.server.model.tables.Crtimezone;
import id.mit.chrono.server.model.tables.Crvendor;
import id.mit.chrono.server.model.tables.Crvendorparamset;
import id.mit.chrono.server.model.tables.Crworkflow;
import id.mit.chrono.server.model.tables.Dailysysinfo2g;
import id.mit.chrono.server.model.tables.Dailysysinfo2gcompare;
import id.mit.chrono.server.model.tables.Dailysysinfo2gcompare2;
import id.mit.chrono.server.model.tables.Erbsc;
import id.mit.chrono.server.model.tables.Erbts;
import id.mit.chrono.server.model.tables.Erenodeb;
import id.mit.chrono.server.model.tables.Ergcell;
import id.mit.chrono.server.model.tables.Ergcellmap;
import id.mit.chrono.server.model.tables.Ergnodeb;
import id.mit.chrono.server.model.tables.Erinventory;
import id.mit.chrono.server.model.tables.Erinventory2;
import id.mit.chrono.server.model.tables.Erlcell;
import id.mit.chrono.server.model.tables.Ermme;
import id.mit.chrono.server.model.tables.Erncell;
import id.mit.chrono.server.model.tables.Ernodeb;
import id.mit.chrono.server.model.tables.Errnc;
import id.mit.chrono.server.model.tables.Erucell;
import id.mit.chrono.server.model.tables.Hwbsc;
import id.mit.chrono.server.model.tables.Hwbscbrd;
import id.mit.chrono.server.model.tables.Hwbsce1t1;
import id.mit.chrono.server.model.tables.Hwbscethport;
import id.mit.chrono.server.model.tables.Hwbts;
import id.mit.chrono.server.model.tables.Hwenodeb;
import id.mit.chrono.server.model.tables.Hwgcell;
import id.mit.chrono.server.model.tables.Hwgnodeb;
import id.mit.chrono.server.model.tables.Hwgtrx;
import id.mit.chrono.server.model.tables.Hwgtrxchan;
import id.mit.chrono.server.model.tables.Hwinventory;
import id.mit.chrono.server.model.tables.Hwlcell;
import id.mit.chrono.server.model.tables.Hwmme;
import id.mit.chrono.server.model.tables.Hwncell;
import id.mit.chrono.server.model.tables.Hwnodeb;
import id.mit.chrono.server.model.tables.Hwrnc;
import id.mit.chrono.server.model.tables.Hwucell;
import id.mit.chrono.server.model.tables.Inventory;
import id.mit.chrono.server.model.tables.Inventoryfieldvalidation;
import id.mit.chrono.server.model.tables.Inventorytype;
import id.mit.chrono.server.model.tables.Lacimareject;
import id.mit.chrono.server.model.tables.MTempsysinfo2g;
import id.mit.chrono.server.model.tables.MTempsysinfo3g;
import id.mit.chrono.server.model.tables.MTempsysinfo4g;
import id.mit.chrono.server.model.tables.Nokbsc;
import id.mit.chrono.server.model.tables.Nokbts;
import id.mit.chrono.server.model.tables.Nokenodeb;
import id.mit.chrono.server.model.tables.Nokgcell;
import id.mit.chrono.server.model.tables.Nokgtrx;
import id.mit.chrono.server.model.tables.Nokinventory;
import id.mit.chrono.server.model.tables.Noklcell;
import id.mit.chrono.server.model.tables.Nokmme;
import id.mit.chrono.server.model.tables.Noknodeb;
import id.mit.chrono.server.model.tables.Nokrnc;
import id.mit.chrono.server.model.tables.Nokucell;
import id.mit.chrono.server.model.tables.SpatialRefSys;
import id.mit.chrono.server.model.tables.Stylogcell;
import id.mit.chrono.server.model.tables.Stylolcell;
import id.mit.chrono.server.model.tables.Styloucell;
import id.mit.chrono.server.model.tables.Temp;
import id.mit.chrono.server.model.tables.TempCrsite;
import id.mit.chrono.server.model.tables.TempCrsite2;
import id.mit.chrono.server.model.tables.TempCrstatic;
import id.mit.chrono.server.model.tables.TempCrstaticCopy;
import id.mit.chrono.server.model.tables.TempXxx;
import id.mit.chrono.server.model.tables.Ztebsc;
import id.mit.chrono.server.model.tables.Ztebscemlppuserpriority;
import id.mit.chrono.server.model.tables.Ztebscextgcell;
import id.mit.chrono.server.model.tables.ZtebscextgcellX;
import id.mit.chrono.server.model.tables.Ztebscextlcell;
import id.mit.chrono.server.model.tables.ZtebscextlcellX;
import id.mit.chrono.server.model.tables.Ztebscextucell;
import id.mit.chrono.server.model.tables.ZtebscextucellX;
import id.mit.chrono.server.model.tables.Ztebsclocarea;
import id.mit.chrono.server.model.tables.Ztebscroutingarea;
import id.mit.chrono.server.model.tables.Ztebts;
import id.mit.chrono.server.model.tables.Zteenodeb;
import id.mit.chrono.server.model.tables.Ztegcell;
import id.mit.chrono.server.model.tables.Ztegcellbvc;
import id.mit.chrono.server.model.tables.Ztegcellpsusrandsrvtype;
import id.mit.chrono.server.model.tables.Ztegcellrelgcell;
import id.mit.chrono.server.model.tables.Ztegcellrellcell;
import id.mit.chrono.server.model.tables.Ztegcellrelucell;
import id.mit.chrono.server.model.tables.Ztegnodeb;
import id.mit.chrono.server.model.tables.Ztegtrx;
import id.mit.chrono.server.model.tables.Ztegts;
import id.mit.chrono.server.model.tables.Zteinventory;
import id.mit.chrono.server.model.tables.Zteinventoryvalidation;
import id.mit.chrono.server.model.tables.Ztelcell;
import id.mit.chrono.server.model.tables.Ztemme;
import id.mit.chrono.server.model.tables.Ztencell;
import id.mit.chrono.server.model.tables.Ztenodeb;
import id.mit.chrono.server.model.tables.Zternc;
import id.mit.chrono.server.model.tables.Zteucell;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in chrono
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>chrono.columnset</code>.
     */
    public static final Columnset COLUMNSET = id.mit.chrono.server.model.tables.Columnset.COLUMNSET;

    /**
     * The table <code>chrono.crantenna</code>.
     */
    public static final Crantenna CRANTENNA = id.mit.chrono.server.model.tables.Crantenna.CRANTENNA;

    /**
     * The table <code>chrono.crantennatype</code>.
     */
    public static final Crantennatype CRANTENNATYPE = id.mit.chrono.server.model.tables.Crantennatype.CRANTENNATYPE;

    /**
     * The table <code>chrono.crappvar</code>.
     */
    public static final Crappvar CRAPPVAR = id.mit.chrono.server.model.tables.Crappvar.CRAPPVAR;

    /**
     * The table <code>chrono.crbrand</code>.
     */
    public static final Crbrand CRBRAND = id.mit.chrono.server.model.tables.Crbrand.CRBRAND;

    /**
     * The table <code>chrono.crcell</code>.
     */
    public static final Crcell CRCELL = id.mit.chrono.server.model.tables.Crcell.CRCELL;

    /**
     * The table <code>chrono.crcellclass</code>.
     */
    public static final Crcellclass CRCELLCLASS = id.mit.chrono.server.model.tables.Crcellclass.CRCELLCLASS;

    /**
     * The table <code>chrono.crcellclassgroup</code>.
     */
    public static final Crcellclassgroup CRCELLCLASSGROUP = id.mit.chrono.server.model.tables.Crcellclassgroup.CRCELLCLASSGROUP;

    /**
     * The table <code>chrono.crcellcoverage</code>.
     */
    public static final Crcellcoverage CRCELLCOVERAGE = id.mit.chrono.server.model.tables.Crcellcoverage.CRCELLCOVERAGE;

    /**
     * The table <code>chrono.crcellnodeid</code>.
     */
    public static final Crcellnodeid CRCELLNODEID = id.mit.chrono.server.model.tables.Crcellnodeid.CRCELLNODEID;

    /**
     * The table <code>chrono.crcellpattern</code>.
     */
    public static final Crcellpattern CRCELLPATTERN = id.mit.chrono.server.model.tables.Crcellpattern.CRCELLPATTERN;

    /**
     * The table <code>chrono.crcellstatus</code>.
     */
    public static final Crcellstatus CRCELLSTATUS = id.mit.chrono.server.model.tables.Crcellstatus.CRCELLSTATUS;

    /**
     * The table <code>chrono.crcollectorstatus</code>.
     */
    public static final Crcollectorstatus CRCOLLECTORSTATUS = id.mit.chrono.server.model.tables.Crcollectorstatus.CRCOLLECTORSTATUS;

    /**
     * The table <code>chrono.crcollectortask</code>.
     */
    public static final Crcollectortask CRCOLLECTORTASK = id.mit.chrono.server.model.tables.Crcollectortask.CRCOLLECTORTASK;

    /**
     * The table <code>chrono.crcollectortaskfiles</code>.
     */
    public static final Crcollectortaskfiles CRCOLLECTORTASKFILES = id.mit.chrono.server.model.tables.Crcollectortaskfiles.CRCOLLECTORTASKFILES;

    /**
     * The table <code>chrono.crcollectortasksources</code>.
     */
    public static final Crcollectortasksources CRCOLLECTORTASKSOURCES = id.mit.chrono.server.model.tables.Crcollectortasksources.CRCOLLECTORTASKSOURCES;

    /**
     * The table <code>chrono.crcompany</code>.
     */
    public static final Crcompany CRCOMPANY = id.mit.chrono.server.model.tables.Crcompany.CRCOMPANY;

    /**
     * The table <code>chrono.crcountry</code>.
     */
    public static final Crcountry CRCOUNTRY = id.mit.chrono.server.model.tables.Crcountry.CRCOUNTRY;

    /**
     * The table <code>chrono.crdataexport</code>.
     */
    public static final Crdataexport CRDATAEXPORT = id.mit.chrono.server.model.tables.Crdataexport.CRDATAEXPORT;

    /**
     * The table <code>chrono.crdataexporttask</code>.
     */
    public static final Crdataexporttask CRDATAEXPORTTASK = id.mit.chrono.server.model.tables.Crdataexporttask.CRDATAEXPORTTASK;

    /**
     * The table <code>chrono.crdataexporttask2</code>.
     */
    public static final Crdataexporttask2 CRDATAEXPORTTASK2 = id.mit.chrono.server.model.tables.Crdataexporttask2.CRDATAEXPORTTASK2;

    /**
     * The table <code>chrono.crdataexporttype</code>.
     */
    public static final Crdataexporttype CRDATAEXPORTTYPE = id.mit.chrono.server.model.tables.Crdataexporttype.CRDATAEXPORTTYPE;

    /**
     * The table <code>chrono.crdatagroup</code>.
     */
    public static final Crdatagroup CRDATAGROUP = id.mit.chrono.server.model.tables.Crdatagroup.CRDATAGROUP;

    /**
     * The table <code>chrono.crdatasource</code>.
     */
    public static final Crdatasource CRDATASOURCE = id.mit.chrono.server.model.tables.Crdatasource.CRDATASOURCE;

    /**
     * The table <code>chrono.crdatasourcecommands</code>.
     */
    public static final Crdatasourcecommands CRDATASOURCECOMMANDS = id.mit.chrono.server.model.tables.Crdatasourcecommands.CRDATASOURCECOMMANDS;

    /**
     * The table <code>chrono.crdatasourcetype</code>.
     */
    public static final Crdatasourcetype CRDATASOURCETYPE = id.mit.chrono.server.model.tables.Crdatasourcetype.CRDATASOURCETYPE;

    /**
     * The table <code>chrono.crdatatype</code>.
     */
    public static final Crdatatype CRDATATYPE = id.mit.chrono.server.model.tables.Crdatatype.CRDATATYPE;

    /**
     * The table <code>chrono.crenodebmme</code>.
     */
    public static final Crenodebmme CRENODEBMME = id.mit.chrono.server.model.tables.Crenodebmme.CRENODEBMME;

    /**
     * The table <code>chrono.crfinalizertask</code>.
     */
    public static final Crfinalizertask CRFINALIZERTASK = id.mit.chrono.server.model.tables.Crfinalizertask.CRFINALIZERTASK;

    /**
     * The table <code>chrono.crfinalizertask_20201023</code>.
     */
    public static final Crfinalizertask_20201023 CRFINALIZERTASK_20201023 = id.mit.chrono.server.model.tables.Crfinalizertask_20201023.CRFINALIZERTASK_20201023;

    /**
     * The table <code>chrono.crflag</code>.
     */
    public static final Crflag CRFLAG = id.mit.chrono.server.model.tables.Crflag.CRFLAG;

    /**
     * The table <code>chrono.crgeomap</code>.
     */
    public static final Crgeomap CRGEOMAP = id.mit.chrono.server.model.tables.Crgeomap.CRGEOMAP;

    /**
     * The table <code>chrono.crgeomap2</code>.
     */
    public static final Crgeomap2 CRGEOMAP2 = id.mit.chrono.server.model.tables.Crgeomap2.CRGEOMAP2;

    /**
     * The table <code>chrono.crgeomap3</code>.
     */
    public static final Crgeomap3 CRGEOMAP3 = id.mit.chrono.server.model.tables.Crgeomap3.CRGEOMAP3;

    /**
     * The table <code>chrono.crisland</code>.
     */
    public static final Crisland CRISLAND = id.mit.chrono.server.model.tables.Crisland.CRISLAND;

    /**
     * The table <code>chrono.crlandstatus</code>.
     */
    public static final Crlandstatus CRLANDSTATUS = id.mit.chrono.server.model.tables.Crlandstatus.CRLANDSTATUS;

    /**
     * The table <code>chrono.crmapentity</code>.
     */
    public static final Crmapentity CRMAPENTITY = id.mit.chrono.server.model.tables.Crmapentity.CRMAPENTITY;

    /**
     * The table <code>chrono.crmapfield</code>.
     */
    public static final Crmapfield CRMAPFIELD = id.mit.chrono.server.model.tables.Crmapfield.CRMAPFIELD;

    /**
     * The table <code>chrono.crmaplevel</code>.
     */
    public static final Crmaplevel CRMAPLEVEL = id.mit.chrono.server.model.tables.Crmaplevel.CRMAPLEVEL;

    /**
     * The table <code>chrono.crmapnptq</code>.
     */
    public static final Crmapnptq CRMAPNPTQ = id.mit.chrono.server.model.tables.Crmapnptq.CRMAPNPTQ;

    /**
     * The table <code>chrono.crmapparser</code>.
     */
    public static final Crmapparser CRMAPPARSER = id.mit.chrono.server.model.tables.Crmapparser.CRMAPPARSER;

    /**
     * The table <code>chrono.crnode</code>.
     */
    public static final Crnode CRNODE = id.mit.chrono.server.model.tables.Crnode.CRNODE;

    /**
     * The table <code>chrono.crnodecalc</code>.
     */
    public static final Crnodecalc CRNODECALC = id.mit.chrono.server.model.tables.Crnodecalc.CRNODECALC;

    /**
     * The table <code>chrono.crnodecategory</code>.
     */
    public static final Crnodecategory CRNODECATEGORY = id.mit.chrono.server.model.tables.Crnodecategory.CRNODECATEGORY;

    /**
     * The table <code>chrono.crnodemaps</code>.
     */
    public static final Crnodemaps CRNODEMAPS = id.mit.chrono.server.model.tables.Crnodemaps.CRNODEMAPS;

    /**
     * The table <code>chrono.crnodepattern</code>.
     */
    public static final Crnodepattern CRNODEPATTERN = id.mit.chrono.server.model.tables.Crnodepattern.CRNODEPATTERN;

    /**
     * The table <code>chrono.crnodeplace</code>.
     */
    public static final Crnodeplace CRNODEPLACE = id.mit.chrono.server.model.tables.Crnodeplace.CRNODEPLACE;

    /**
     * The table <code>chrono.crnodestate</code>.
     */
    public static final Crnodestate CRNODESTATE = id.mit.chrono.server.model.tables.Crnodestate.CRNODESTATE;

    /**
     * The table <code>chrono.crnodestatus</code>.
     */
    public static final Crnodestatus CRNODESTATUS = id.mit.chrono.server.model.tables.Crnodestatus.CRNODESTATUS;

    /**
     * The table <code>chrono.crnodetype</code>.
     */
    public static final Crnodetype CRNODETYPE = id.mit.chrono.server.model.tables.Crnodetype.CRNODETYPE;

    /**
     * The table <code>chrono.crnptq</code>.
     */
    public static final Crnptq CRNPTQ = id.mit.chrono.server.model.tables.Crnptq.CRNPTQ;

    /**
     * The table <code>chrono.crobject</code>.
     */
    public static final Crobject CROBJECT = id.mit.chrono.server.model.tables.Crobject.CROBJECT;

    /**
     * The table <code>chrono.crobjectcategory</code>.
     */
    public static final Crobjectcategory CROBJECTCATEGORY = id.mit.chrono.server.model.tables.Crobjectcategory.CROBJECTCATEGORY;

    /**
     * The table <code>chrono.crprocessorstatistic</code>.
     */
    public static final Crprocessorstatistic CRPROCESSORSTATISTIC = id.mit.chrono.server.model.tables.Crprocessorstatistic.CRPROCESSORSTATISTIC;

    /**
     * The table <code>chrono.crprocessortaskfiles</code>.
     */
    public static final Crprocessortaskfiles CRPROCESSORTASKFILES = id.mit.chrono.server.model.tables.Crprocessortaskfiles.CRPROCESSORTASKFILES;

    /**
     * The table <code>chrono.crprocessstatus</code>.
     */
    public static final Crprocessstatus CRPROCESSSTATUS = id.mit.chrono.server.model.tables.Crprocessstatus.CRPROCESSSTATUS;

    /**
     * The table <code>chrono.crprovince</code>.
     */
    public static final Crprovince CRPROVINCE = id.mit.chrono.server.model.tables.Crprovince.CRPROVINCE;

    /**
     * The table <code>chrono.crqueryset</code>.
     */
    public static final Crqueryset CRQUERYSET = id.mit.chrono.server.model.tables.Crqueryset.CRQUERYSET;

    /**
     * The table <code>chrono.crranbts</code>.
     */
    public static final Crranbts CRRANBTS = id.mit.chrono.server.model.tables.Crranbts.CRRANBTS;

    /**
     * The table <code>chrono.crrancell</code>.
     */
    public static final Crrancell CRRANCELL = id.mit.chrono.server.model.tables.Crrancell.CRRANCELL;

    /**
     * The table <code>chrono.crrancelladv</code>.
     */
    public static final Crrancelladv CRRANCELLADV = id.mit.chrono.server.model.tables.Crrancelladv.CRRANCELLADV;

    /**
     * The table <code>chrono.crrancontroller</code>.
     */
    public static final Crrancontroller CRRANCONTROLLER = id.mit.chrono.server.model.tables.Crrancontroller.CRRANCONTROLLER;

    /**
     * The table <code>chrono.crrelsitesitearea</code>.
     */
    public static final Crrelsitesitearea CRRELSITESITEAREA = id.mit.chrono.server.model.tables.Crrelsitesitearea.CRRELSITESITEAREA;

    /**
     * The table <code>chrono.crrevenueclass</code>.
     */
    public static final Crrevenueclass CRREVENUECLASS = id.mit.chrono.server.model.tables.Crrevenueclass.CRREVENUECLASS;

    /**
     * The table <code>chrono.crsettings</code>.
     */
    public static final Crsettings CRSETTINGS = id.mit.chrono.server.model.tables.Crsettings.CRSETTINGS;

    /**
     * The table <code>chrono.crsite</code>.
     */
    public static final Crsite CRSITE = id.mit.chrono.server.model.tables.Crsite.CRSITE;

    /**
     * The table <code>chrono.crsitearea</code>.
     */
    public static final Crsitearea CRSITEAREA = id.mit.chrono.server.model.tables.Crsitearea.CRSITEAREA;

    /**
     * The table <code>chrono.crsitearea_old</code>.
     */
    public static final CrsiteareaOld CRSITEAREA_OLD = id.mit.chrono.server.model.tables.CrsiteareaOld.CRSITEAREA_OLD;

    /**
     * The table <code>chrono.crsiteflags</code>.
     */
    public static final Crsiteflags CRSITEFLAGS = id.mit.chrono.server.model.tables.Crsiteflags.CRSITEFLAGS;

    /**
     * The table <code>chrono.crsiteprefix</code>.
     */
    public static final Crsiteprefix CRSITEPREFIX = id.mit.chrono.server.model.tables.Crsiteprefix.CRSITEPREFIX;

    /**
     * The table <code>chrono.crsitestate</code>.
     */
    public static final Crsitestate CRSITESTATE = id.mit.chrono.server.model.tables.Crsitestate.CRSITESTATE;

    /**
     * The table <code>chrono.crsitetype</code>.
     */
    public static final Crsitetype CRSITETYPE = id.mit.chrono.server.model.tables.Crsitetype.CRSITETYPE;

    /**
     * The table <code>chrono.crsite_old</code>.
     */
    public static final CrsiteOld CRSITE_OLD = id.mit.chrono.server.model.tables.CrsiteOld.CRSITE_OLD;

    /**
     * The table <code>chrono.crsourceparser</code>.
     */
    public static final Crsourceparser CRSOURCEPARSER = id.mit.chrono.server.model.tables.Crsourceparser.CRSOURCEPARSER;

    /**
     * The table <code>chrono.crstaticgcell</code>.
     */
    public static final Crstaticgcell CRSTATICGCELL = id.mit.chrono.server.model.tables.Crstaticgcell.CRSTATICGCELL;

    /**
     * The table <code>chrono.crstaticgcell_copy</code>.
     */
    public static final CrstaticgcellCopy CRSTATICGCELL_COPY = id.mit.chrono.server.model.tables.CrstaticgcellCopy.CRSTATICGCELL_COPY;

    /**
     * The table <code>chrono.crstaticlcell</code>.
     */
    public static final Crstaticlcell CRSTATICLCELL = id.mit.chrono.server.model.tables.Crstaticlcell.CRSTATICLCELL;

    /**
     * The table <code>chrono.crstaticlcell_copy</code>.
     */
    public static final CrstaticlcellCopy CRSTATICLCELL_COPY = id.mit.chrono.server.model.tables.CrstaticlcellCopy.CRSTATICLCELL_COPY;

    /**
     * The table <code>chrono.crstaticucell</code>.
     */
    public static final Crstaticucell CRSTATICUCELL = id.mit.chrono.server.model.tables.Crstaticucell.CRSTATICUCELL;

    /**
     * The table <code>chrono.crsubdistrict</code>.
     */
    public static final Crsubdistrict CRSUBDISTRICT = id.mit.chrono.server.model.tables.Crsubdistrict.CRSUBDISTRICT;

    /**
     * The table <code>chrono.crsummaryarea</code>.
     */
    public static final Crsummaryarea CRSUMMARYAREA = id.mit.chrono.server.model.tables.Crsummaryarea.CRSUMMARYAREA;

    /**
     * The table <code>chrono.crsummarynation</code>.
     */
    public static final Crsummarynation CRSUMMARYNATION = id.mit.chrono.server.model.tables.Crsummarynation.CRSUMMARYNATION;

    /**
     * The table <code>chrono.crsummaryoss</code>.
     */
    public static final Crsummaryoss CRSUMMARYOSS = id.mit.chrono.server.model.tables.Crsummaryoss.CRSUMMARYOSS;

    /**
     * The table <code>chrono.crsummaryregional</code>.
     */
    public static final Crsummaryregional CRSUMMARYREGIONAL = id.mit.chrono.server.model.tables.Crsummaryregional.CRSUMMARYREGIONAL;

    /**
     * The table <code>chrono.crsummaryvendor</code>.
     */
    public static final Crsummaryvendor CRSUMMARYVENDOR = id.mit.chrono.server.model.tables.Crsummaryvendor.CRSUMMARYVENDOR;

    /**
     * The table <code>chrono.crtest</code>.
     */
    public static final Crtest CRTEST = id.mit.chrono.server.model.tables.Crtest.CRTEST;

    /**
     * The table <code>chrono.crtimecatalog</code>.
     */
    public static final Crtimecatalog CRTIMECATALOG = id.mit.chrono.server.model.tables.Crtimecatalog.CRTIMECATALOG;

    /**
     * The table <code>chrono.crtimezone</code>.
     */
    public static final Crtimezone CRTIMEZONE = id.mit.chrono.server.model.tables.Crtimezone.CRTIMEZONE;

    /**
     * The table <code>chrono.crvendor</code>.
     */
    public static final Crvendor CRVENDOR = id.mit.chrono.server.model.tables.Crvendor.CRVENDOR;

    /**
     * The table <code>chrono.crvendorparamset</code>.
     */
    public static final Crvendorparamset CRVENDORPARAMSET = id.mit.chrono.server.model.tables.Crvendorparamset.CRVENDORPARAMSET;

    /**
     * The table <code>chrono.crworkflow</code>.
     */
    public static final Crworkflow CRWORKFLOW = id.mit.chrono.server.model.tables.Crworkflow.CRWORKFLOW;

    /**
     * The table <code>chrono.DailySysinfo2G</code>.
     */
    public static final Dailysysinfo2g DAILYSYSINFO2G = id.mit.chrono.server.model.tables.Dailysysinfo2g.DAILYSYSINFO2G;

    /**
     * The table <code>chrono.DailySysinfo2GCompare</code>.
     */
    public static final Dailysysinfo2gcompare DAILYSYSINFO2GCOMPARE = id.mit.chrono.server.model.tables.Dailysysinfo2gcompare.DAILYSYSINFO2GCOMPARE;

    /**
     * The table <code>chrono.DailySysinfo2GCompare2</code>.
     */
    public static final Dailysysinfo2gcompare2 DAILYSYSINFO2GCOMPARE2 = id.mit.chrono.server.model.tables.Dailysysinfo2gcompare2.DAILYSYSINFO2GCOMPARE2;

    /**
     * The table <code>chrono.erbsc</code>.
     */
    public static final Erbsc ERBSC = id.mit.chrono.server.model.tables.Erbsc.ERBSC;

    /**
     * The table <code>chrono.erbts</code>.
     */
    public static final Erbts ERBTS = id.mit.chrono.server.model.tables.Erbts.ERBTS;

    /**
     * The table <code>chrono.erenodeb</code>.
     */
    public static final Erenodeb ERENODEB = id.mit.chrono.server.model.tables.Erenodeb.ERENODEB;

    /**
     * The table <code>chrono.ergcell</code>.
     */
    public static final Ergcell ERGCELL = id.mit.chrono.server.model.tables.Ergcell.ERGCELL;

    /**
     * The table <code>chrono.ergcellmap</code>.
     */
    public static final Ergcellmap ERGCELLMAP = id.mit.chrono.server.model.tables.Ergcellmap.ERGCELLMAP;

    /**
     * The table <code>chrono.ergnodeb</code>.
     */
    public static final Ergnodeb ERGNODEB = id.mit.chrono.server.model.tables.Ergnodeb.ERGNODEB;

    /**
     * The table <code>chrono.erinventory</code>.
     */
    public static final Erinventory ERINVENTORY = id.mit.chrono.server.model.tables.Erinventory.ERINVENTORY;

    /**
     * The table <code>chrono.erinventory2</code>.
     */
    public static final Erinventory2 ERINVENTORY2 = id.mit.chrono.server.model.tables.Erinventory2.ERINVENTORY2;

    /**
     * The table <code>chrono.erlcell</code>.
     */
    public static final Erlcell ERLCELL = id.mit.chrono.server.model.tables.Erlcell.ERLCELL;

    /**
     * The table <code>chrono.ermme</code>.
     */
    public static final Ermme ERMME = id.mit.chrono.server.model.tables.Ermme.ERMME;

    /**
     * The table <code>chrono.erncell</code>.
     */
    public static final Erncell ERNCELL = id.mit.chrono.server.model.tables.Erncell.ERNCELL;

    /**
     * The table <code>chrono.ernodeb</code>.
     */
    public static final Ernodeb ERNODEB = id.mit.chrono.server.model.tables.Ernodeb.ERNODEB;

    /**
     * The table <code>chrono.errnc</code>.
     */
    public static final Errnc ERRNC = id.mit.chrono.server.model.tables.Errnc.ERRNC;

    /**
     * The table <code>chrono.erucell</code>.
     */
    public static final Erucell ERUCELL = id.mit.chrono.server.model.tables.Erucell.ERUCELL;

    /**
     * The table <code>chrono.hwbsc</code>.
     */
    public static final Hwbsc HWBSC = id.mit.chrono.server.model.tables.Hwbsc.HWBSC;

    /**
     * The table <code>chrono.hwbscbrd</code>.
     */
    public static final Hwbscbrd HWBSCBRD = id.mit.chrono.server.model.tables.Hwbscbrd.HWBSCBRD;

    /**
     * The table <code>chrono.hwbsce1t1</code>.
     */
    public static final Hwbsce1t1 HWBSCE1T1 = id.mit.chrono.server.model.tables.Hwbsce1t1.HWBSCE1T1;

    /**
     * The table <code>chrono.hwbscethport</code>.
     */
    public static final Hwbscethport HWBSCETHPORT = id.mit.chrono.server.model.tables.Hwbscethport.HWBSCETHPORT;

    /**
     * The table <code>chrono.hwbts</code>.
     */
    public static final Hwbts HWBTS = id.mit.chrono.server.model.tables.Hwbts.HWBTS;

    /**
     * The table <code>chrono.hwenodeb</code>.
     */
    public static final Hwenodeb HWENODEB = id.mit.chrono.server.model.tables.Hwenodeb.HWENODEB;

    /**
     * The table <code>chrono.hwgcell</code>.
     */
    public static final Hwgcell HWGCELL = id.mit.chrono.server.model.tables.Hwgcell.HWGCELL;

    /**
     * The table <code>chrono.hwgnodeb</code>.
     */
    public static final Hwgnodeb HWGNODEB = id.mit.chrono.server.model.tables.Hwgnodeb.HWGNODEB;

    /**
     * The table <code>chrono.hwgtrx</code>.
     */
    public static final Hwgtrx HWGTRX = id.mit.chrono.server.model.tables.Hwgtrx.HWGTRX;

    /**
     * The table <code>chrono.hwgtrxchan</code>.
     */
    public static final Hwgtrxchan HWGTRXCHAN = id.mit.chrono.server.model.tables.Hwgtrxchan.HWGTRXCHAN;

    /**
     * The table <code>chrono.hwinventory</code>.
     */
    public static final Hwinventory HWINVENTORY = id.mit.chrono.server.model.tables.Hwinventory.HWINVENTORY;

    /**
     * The table <code>chrono.hwlcell</code>.
     */
    public static final Hwlcell HWLCELL = id.mit.chrono.server.model.tables.Hwlcell.HWLCELL;

    /**
     * The table <code>chrono.hwmme</code>.
     */
    public static final Hwmme HWMME = id.mit.chrono.server.model.tables.Hwmme.HWMME;

    /**
     * The table <code>chrono.hwncell</code>.
     */
    public static final Hwncell HWNCELL = id.mit.chrono.server.model.tables.Hwncell.HWNCELL;

    /**
     * The table <code>chrono.hwnodeb</code>.
     */
    public static final Hwnodeb HWNODEB = id.mit.chrono.server.model.tables.Hwnodeb.HWNODEB;

    /**
     * The table <code>chrono.hwrnc</code>.
     */
    public static final Hwrnc HWRNC = id.mit.chrono.server.model.tables.Hwrnc.HWRNC;

    /**
     * The table <code>chrono.hwucell</code>.
     */
    public static final Hwucell HWUCELL = id.mit.chrono.server.model.tables.Hwucell.HWUCELL;

    /**
     * The table <code>chrono.inventory</code>.
     */
    public static final Inventory INVENTORY = id.mit.chrono.server.model.tables.Inventory.INVENTORY;

    /**
     * The table <code>chrono.inventoryfieldvalidation</code>.
     */
    public static final Inventoryfieldvalidation INVENTORYFIELDVALIDATION = id.mit.chrono.server.model.tables.Inventoryfieldvalidation.INVENTORYFIELDVALIDATION;

    /**
     * The table <code>chrono.inventorytype</code>.
     */
    public static final Inventorytype INVENTORYTYPE = id.mit.chrono.server.model.tables.Inventorytype.INVENTORYTYPE;

    /**
     * The table <code>chrono.lacimareject</code>.
     */
    public static final Lacimareject LACIMAREJECT = id.mit.chrono.server.model.tables.Lacimareject.LACIMAREJECT;

    /**
     * The table <code>chrono.m_tempsysinfo2G</code>.
     */
    public static final MTempsysinfo2g M_TEMPSYSINFO2G = id.mit.chrono.server.model.tables.MTempsysinfo2g.M_TEMPSYSINFO2G;

    /**
     * The table <code>chrono.m_tempsysinfo3G</code>.
     */
    public static final MTempsysinfo3g M_TEMPSYSINFO3G = id.mit.chrono.server.model.tables.MTempsysinfo3g.M_TEMPSYSINFO3G;

    /**
     * The table <code>chrono.m_tempsysinfo4G</code>.
     */
    public static final MTempsysinfo4g M_TEMPSYSINFO4G = id.mit.chrono.server.model.tables.MTempsysinfo4g.M_TEMPSYSINFO4G;

    /**
     * The table <code>chrono.nokbsc</code>.
     */
    public static final Nokbsc NOKBSC = id.mit.chrono.server.model.tables.Nokbsc.NOKBSC;

    /**
     * The table <code>chrono.nokbts</code>.
     */
    public static final Nokbts NOKBTS = id.mit.chrono.server.model.tables.Nokbts.NOKBTS;

    /**
     * The table <code>chrono.nokenodeb</code>.
     */
    public static final Nokenodeb NOKENODEB = id.mit.chrono.server.model.tables.Nokenodeb.NOKENODEB;

    /**
     * The table <code>chrono.nokgcell</code>.
     */
    public static final Nokgcell NOKGCELL = id.mit.chrono.server.model.tables.Nokgcell.NOKGCELL;

    /**
     * The table <code>chrono.nokgtrx</code>.
     */
    public static final Nokgtrx NOKGTRX = id.mit.chrono.server.model.tables.Nokgtrx.NOKGTRX;

    /**
     * The table <code>chrono.nokinventory</code>.
     */
    public static final Nokinventory NOKINVENTORY = id.mit.chrono.server.model.tables.Nokinventory.NOKINVENTORY;

    /**
     * The table <code>chrono.noklcell</code>.
     */
    public static final Noklcell NOKLCELL = id.mit.chrono.server.model.tables.Noklcell.NOKLCELL;

    /**
     * The table <code>chrono.nokmme</code>.
     */
    public static final Nokmme NOKMME = id.mit.chrono.server.model.tables.Nokmme.NOKMME;

    /**
     * The table <code>chrono.noknodeb</code>.
     */
    public static final Noknodeb NOKNODEB = id.mit.chrono.server.model.tables.Noknodeb.NOKNODEB;

    /**
     * The table <code>chrono.nokrnc</code>.
     */
    public static final Nokrnc NOKRNC = id.mit.chrono.server.model.tables.Nokrnc.NOKRNC;

    /**
     * The table <code>chrono.nokucell</code>.
     */
    public static final Nokucell NOKUCELL = id.mit.chrono.server.model.tables.Nokucell.NOKUCELL;

    /**
     * The table <code>chrono.spatial_ref_sys</code>.
     */
    public static final SpatialRefSys SPATIAL_REF_SYS = id.mit.chrono.server.model.tables.SpatialRefSys.SPATIAL_REF_SYS;

    /**
     * The table <code>chrono.stylogcell</code>.
     */
    public static final Stylogcell STYLOGCELL = id.mit.chrono.server.model.tables.Stylogcell.STYLOGCELL;

    /**
     * The table <code>chrono.stylolcell</code>.
     */
    public static final Stylolcell STYLOLCELL = id.mit.chrono.server.model.tables.Stylolcell.STYLOLCELL;

    /**
     * The table <code>chrono.styloucell</code>.
     */
    public static final Styloucell STYLOUCELL = id.mit.chrono.server.model.tables.Styloucell.STYLOUCELL;

    /**
     * The table <code>chrono.temp</code>.
     */
    public static final Temp TEMP = id.mit.chrono.server.model.tables.Temp.TEMP;

    /**
     * The table <code>chrono.temp_crsite</code>.
     */
    public static final TempCrsite TEMP_CRSITE = id.mit.chrono.server.model.tables.TempCrsite.TEMP_CRSITE;

    /**
     * The table <code>chrono.temp_crsite2</code>.
     */
    public static final TempCrsite2 TEMP_CRSITE2 = id.mit.chrono.server.model.tables.TempCrsite2.TEMP_CRSITE2;

    /**
     * The table <code>chrono.temp_crstatic</code>.
     */
    public static final TempCrstatic TEMP_CRSTATIC = id.mit.chrono.server.model.tables.TempCrstatic.TEMP_CRSTATIC;

    /**
     * The table <code>chrono.temp_crstatic_copy</code>.
     */
    public static final TempCrstaticCopy TEMP_CRSTATIC_COPY = id.mit.chrono.server.model.tables.TempCrstaticCopy.TEMP_CRSTATIC_COPY;

    /**
     * The table <code>chrono.temp_xxx</code>.
     */
    public static final TempXxx TEMP_XXX = id.mit.chrono.server.model.tables.TempXxx.TEMP_XXX;

    /**
     * The table <code>chrono.ztebsc</code>.
     */
    public static final Ztebsc ZTEBSC = id.mit.chrono.server.model.tables.Ztebsc.ZTEBSC;

    /**
     * The table <code>chrono.ztebscemlppuserpriority</code>.
     */
    public static final Ztebscemlppuserpriority ZTEBSCEMLPPUSERPRIORITY = id.mit.chrono.server.model.tables.Ztebscemlppuserpriority.ZTEBSCEMLPPUSERPRIORITY;

    /**
     * The table <code>chrono.ztebscextgcell</code>.
     */
    public static final Ztebscextgcell ZTEBSCEXTGCELL = id.mit.chrono.server.model.tables.Ztebscextgcell.ZTEBSCEXTGCELL;

    /**
     * The table <code>chrono.ztebscextgcell_x</code>.
     */
    public static final ZtebscextgcellX ZTEBSCEXTGCELL_X = id.mit.chrono.server.model.tables.ZtebscextgcellX.ZTEBSCEXTGCELL_X;

    /**
     * The table <code>chrono.ztebscextlcell</code>.
     */
    public static final Ztebscextlcell ZTEBSCEXTLCELL = id.mit.chrono.server.model.tables.Ztebscextlcell.ZTEBSCEXTLCELL;

    /**
     * The table <code>chrono.ztebscextlcell_x</code>.
     */
    public static final ZtebscextlcellX ZTEBSCEXTLCELL_X = id.mit.chrono.server.model.tables.ZtebscextlcellX.ZTEBSCEXTLCELL_X;

    /**
     * The table <code>chrono.ztebscextucell</code>.
     */
    public static final Ztebscextucell ZTEBSCEXTUCELL = id.mit.chrono.server.model.tables.Ztebscextucell.ZTEBSCEXTUCELL;

    /**
     * The table <code>chrono.ztebscextucell_x</code>.
     */
    public static final ZtebscextucellX ZTEBSCEXTUCELL_X = id.mit.chrono.server.model.tables.ZtebscextucellX.ZTEBSCEXTUCELL_X;

    /**
     * The table <code>chrono.ztebsclocarea</code>.
     */
    public static final Ztebsclocarea ZTEBSCLOCAREA = id.mit.chrono.server.model.tables.Ztebsclocarea.ZTEBSCLOCAREA;

    /**
     * The table <code>chrono.ztebscroutingarea</code>.
     */
    public static final Ztebscroutingarea ZTEBSCROUTINGAREA = id.mit.chrono.server.model.tables.Ztebscroutingarea.ZTEBSCROUTINGAREA;

    /**
     * The table <code>chrono.ztebts</code>.
     */
    public static final Ztebts ZTEBTS = id.mit.chrono.server.model.tables.Ztebts.ZTEBTS;

    /**
     * The table <code>chrono.zteenodeb</code>.
     */
    public static final Zteenodeb ZTEENODEB = id.mit.chrono.server.model.tables.Zteenodeb.ZTEENODEB;

    /**
     * The table <code>chrono.ztegcell</code>.
     */
    public static final Ztegcell ZTEGCELL = id.mit.chrono.server.model.tables.Ztegcell.ZTEGCELL;

    /**
     * The table <code>chrono.ztegcellbvc</code>.
     */
    public static final Ztegcellbvc ZTEGCELLBVC = id.mit.chrono.server.model.tables.Ztegcellbvc.ZTEGCELLBVC;

    /**
     * The table <code>chrono.ztegcellpsusrandsrvtype</code>.
     */
    public static final Ztegcellpsusrandsrvtype ZTEGCELLPSUSRANDSRVTYPE = id.mit.chrono.server.model.tables.Ztegcellpsusrandsrvtype.ZTEGCELLPSUSRANDSRVTYPE;

    /**
     * The table <code>chrono.ztegcellrelgcell</code>.
     */
    public static final Ztegcellrelgcell ZTEGCELLRELGCELL = id.mit.chrono.server.model.tables.Ztegcellrelgcell.ZTEGCELLRELGCELL;

    /**
     * The table <code>chrono.ztegcellrellcell</code>.
     */
    public static final Ztegcellrellcell ZTEGCELLRELLCELL = id.mit.chrono.server.model.tables.Ztegcellrellcell.ZTEGCELLRELLCELL;

    /**
     * The table <code>chrono.ztegcellrelucell</code>.
     */
    public static final Ztegcellrelucell ZTEGCELLRELUCELL = id.mit.chrono.server.model.tables.Ztegcellrelucell.ZTEGCELLRELUCELL;

    /**
     * The table <code>chrono.ztegnodeb</code>.
     */
    public static final Ztegnodeb ZTEGNODEB = id.mit.chrono.server.model.tables.Ztegnodeb.ZTEGNODEB;

    /**
     * The table <code>chrono.ztegtrx</code>.
     */
    public static final Ztegtrx ZTEGTRX = id.mit.chrono.server.model.tables.Ztegtrx.ZTEGTRX;

    /**
     * The table <code>chrono.ztegts</code>.
     */
    public static final Ztegts ZTEGTS = id.mit.chrono.server.model.tables.Ztegts.ZTEGTS;

    /**
     * The table <code>chrono.zteinventory</code>.
     */
    public static final Zteinventory ZTEINVENTORY = id.mit.chrono.server.model.tables.Zteinventory.ZTEINVENTORY;

    /**
     * The table <code>chrono.zteinventoryvalidation</code>.
     */
    public static final Zteinventoryvalidation ZTEINVENTORYVALIDATION = id.mit.chrono.server.model.tables.Zteinventoryvalidation.ZTEINVENTORYVALIDATION;

    /**
     * The table <code>chrono.ztelcell</code>.
     */
    public static final Ztelcell ZTELCELL = id.mit.chrono.server.model.tables.Ztelcell.ZTELCELL;

    /**
     * The table <code>chrono.ztemme</code>.
     */
    public static final Ztemme ZTEMME = id.mit.chrono.server.model.tables.Ztemme.ZTEMME;

    /**
     * The table <code>chrono.ztencell</code>.
     */
    public static final Ztencell ZTENCELL = id.mit.chrono.server.model.tables.Ztencell.ZTENCELL;

    /**
     * The table <code>chrono.ztenodeb</code>.
     */
    public static final Ztenodeb ZTENODEB = id.mit.chrono.server.model.tables.Ztenodeb.ZTENODEB;

    /**
     * The table <code>chrono.zternc</code>.
     */
    public static final Zternc ZTERNC = id.mit.chrono.server.model.tables.Zternc.ZTERNC;

    /**
     * The table <code>chrono.zteucell</code>.
     */
    public static final Zteucell ZTEUCELL = id.mit.chrono.server.model.tables.Zteucell.ZTEUCELL;
}
