/*
 * This file is generated by jOOQ.
*/
package id.mit.chrono.server.model.tables;


import id.mit.chrono.server.model.Chrono;
import id.mit.chrono.server.model.Indexes;
import id.mit.chrono.server.model.Keys;
import id.mit.chrono.server.model.tables.records.CrmapentityRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Crmapentity extends TableImpl<CrmapentityRecord> {

    private static final long serialVersionUID = -1156433881;

    /**
     * The reference instance of <code>chrono.crmapentity</code>
     */
    public static final Crmapentity CRMAPENTITY = new Crmapentity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CrmapentityRecord> getRecordType() {
        return CrmapentityRecord.class;
    }

    /**
     * The column <code>chrono.crmapentity.mapentity_id</code>.
     */
    public final TableField<CrmapentityRecord, Integer> MAPENTITY_ID = createField("mapentity_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>chrono.crmapentity.mapentity_code</code>.
     */
    public final TableField<CrmapentityRecord, String> MAPENTITY_CODE = createField("mapentity_code", org.jooq.impl.SQLDataType.CHAR(32), this, "");

    /**
     * The column <code>chrono.crmapentity.mapentity_parent</code>.
     */
    public final TableField<CrmapentityRecord, Integer> MAPENTITY_PARENT = createField("mapentity_parent", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.crmapentity.mapentity_datagroup</code>.
     */
    public final TableField<CrmapentityRecord, Integer> MAPENTITY_DATAGROUP = createField("mapentity_datagroup", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.crmapentity.mapentity_vendor</code>.
     */
    public final TableField<CrmapentityRecord, Integer> MAPENTITY_VENDOR = createField("mapentity_vendor", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.crmapentity.mapentity_maplevel</code>.
     */
    public final TableField<CrmapentityRecord, Integer> MAPENTITY_MAPLEVEL = createField("mapentity_maplevel", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.crmapentity.mapentity_tablename</code>.
     */
    public final TableField<CrmapentityRecord, String> MAPENTITY_TABLENAME = createField("mapentity_tablename", org.jooq.impl.SQLDataType.CHAR(32), this, "");

    /**
     * The column <code>chrono.crmapentity.mapentity_filepattern</code>.
     */
    public final TableField<CrmapentityRecord, String> MAPENTITY_FILEPATTERN = createField("mapentity_filepattern", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>chrono.crmapentity.mapentity_fileselector</code>.
     */
    public final TableField<CrmapentityRecord, String> MAPENTITY_FILESELECTOR = createField("mapentity_fileselector", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>chrono.crmapentity.mapentity_filereducer</code>.
     */
    public final TableField<CrmapentityRecord, String> MAPENTITY_FILEREDUCER = createField("mapentity_filereducer", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>chrono.crmapentity.mapentity_nodecategory</code>.
     */
    public final TableField<CrmapentityRecord, Integer> MAPENTITY_NODECATEGORY = createField("mapentity_nodecategory", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.crmapentity.mapentity_enabled</code>.
     */
    public final TableField<CrmapentityRecord, Byte> MAPENTITY_ENABLED = createField("mapentity_enabled", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * Create a <code>chrono.crmapentity</code> table reference
     */
    public Crmapentity() {
        this(DSL.name("crmapentity"), null);
    }

    /**
     * Create an aliased <code>chrono.crmapentity</code> table reference
     */
    public Crmapentity(String alias) {
        this(DSL.name(alias), CRMAPENTITY);
    }

    /**
     * Create an aliased <code>chrono.crmapentity</code> table reference
     */
    public Crmapentity(Name alias) {
        this(alias, CRMAPENTITY);
    }

    private Crmapentity(Name alias, Table<CrmapentityRecord> aliased) {
        this(alias, aliased, null);
    }

    private Crmapentity(Name alias, Table<CrmapentityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Chrono.CHRONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CRMAPENTITY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CrmapentityRecord> getPrimaryKey() {
        return Keys.KEY_CRMAPENTITY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CrmapentityRecord>> getKeys() {
        return Arrays.<UniqueKey<CrmapentityRecord>>asList(Keys.KEY_CRMAPENTITY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Crmapentity as(String alias) {
        return new Crmapentity(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Crmapentity as(Name alias) {
        return new Crmapentity(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Crmapentity rename(String name) {
        return new Crmapentity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Crmapentity rename(Name name) {
        return new Crmapentity(name, null);
    }
}
