/*
 * This file is generated by jOOQ.
*/
package id.mit.chrono.server.model.tables;


import id.mit.chrono.server.model.Chrono;
import id.mit.chrono.server.model.Indexes;
import id.mit.chrono.server.model.Keys;
import id.mit.chrono.server.model.tables.records.CrrelsitesiteareaRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Crrelsitesitearea extends TableImpl<CrrelsitesiteareaRecord> {

    private static final long serialVersionUID = -1734613719;

    /**
     * The reference instance of <code>chrono.crrelsitesitearea</code>
     */
    public static final Crrelsitesitearea CRRELSITESITEAREA = new Crrelsitesitearea();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CrrelsitesiteareaRecord> getRecordType() {
        return CrrelsitesiteareaRecord.class;
    }

    /**
     * The column <code>chrono.crrelsitesitearea.relsitesitearea_id</code>.
     */
    public final TableField<CrrelsitesiteareaRecord, UInteger> RELSITESITEAREA_ID = createField("relsitesitearea_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>chrono.crrelsitesitearea.relsitesitearea_site</code>.
     */
    public final TableField<CrrelsitesiteareaRecord, Integer> RELSITESITEAREA_SITE = createField("relsitesitearea_site", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.crrelsitesitearea.relsitesitearea_sitearea</code>.
     */
    public final TableField<CrrelsitesiteareaRecord, Integer> RELSITESITEAREA_SITEAREA = createField("relsitesitearea_sitearea", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.crrelsitesitearea.relsitesitearea_istemporary</code>.
     */
    public final TableField<CrrelsitesiteareaRecord, Byte> RELSITESITEAREA_ISTEMPORARY = createField("relsitesitearea_istemporary", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * Create a <code>chrono.crrelsitesitearea</code> table reference
     */
    public Crrelsitesitearea() {
        this(DSL.name("crrelsitesitearea"), null);
    }

    /**
     * Create an aliased <code>chrono.crrelsitesitearea</code> table reference
     */
    public Crrelsitesitearea(String alias) {
        this(DSL.name(alias), CRRELSITESITEAREA);
    }

    /**
     * Create an aliased <code>chrono.crrelsitesitearea</code> table reference
     */
    public Crrelsitesitearea(Name alias) {
        this(alias, CRRELSITESITEAREA);
    }

    private Crrelsitesitearea(Name alias, Table<CrrelsitesiteareaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Crrelsitesitearea(Name alias, Table<CrrelsitesiteareaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Chrono.CHRONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CRRELSITESITEAREA_M_SITEOPERATOR_SITEAREA2SITEAREA_SITEAREA_ID, Indexes.CRRELSITESITEAREA_M_SITEOPERATOR_SITEAREA2SITEAREA_SITEOPERATOR_ID, Indexes.CRRELSITESITEAREA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CrrelsitesiteareaRecord> getPrimaryKey() {
        return Keys.KEY_CRRELSITESITEAREA_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CrrelsitesiteareaRecord>> getKeys() {
        return Arrays.<UniqueKey<CrrelsitesiteareaRecord>>asList(Keys.KEY_CRRELSITESITEAREA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Crrelsitesitearea as(String alias) {
        return new Crrelsitesitearea(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Crrelsitesitearea as(Name alias) {
        return new Crrelsitesitearea(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Crrelsitesitearea rename(String name) {
        return new Crrelsitesitearea(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Crrelsitesitearea rename(Name name) {
        return new Crrelsitesitearea(name, null);
    }
}
