/*
 * This file is generated by jOOQ.
*/
package id.mit.chrono.server.model.tables;


import id.mit.chrono.server.model.Chrono;
import id.mit.chrono.server.model.Keys;
import id.mit.chrono.server.model.tables.records.HwncellRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hwncell extends TableImpl<HwncellRecord> {

    private static final long serialVersionUID = -986863235;

    /**
     * The reference instance of <code>chrono.hwncell</code>
     */
    public static final Hwncell HWNCELL = new Hwncell();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HwncellRecord> getRecordType() {
        return HwncellRecord.class;
    }

    /**
     * The column <code>chrono.hwncell.hwncell_id</code>.
     */
    public final TableField<HwncellRecord, ULong> HWNCELL_ID = createField("hwncell_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>chrono.hwncell.hwncell_crcollectortaskfiles</code>.
     */
    public final TableField<HwncellRecord, ULong> HWNCELL_CRCOLLECTORTASKFILES = createField("hwncell_crcollectortaskfiles", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * The column <code>chrono.hwncell.hwncell_date</code>.
     */
    public final TableField<HwncellRecord, UInteger> HWNCELL_DATE = createField("hwncell_date", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>chrono.hwncell.hwncell_datefrom</code>.
     */
    public final TableField<HwncellRecord, Integer> HWNCELL_DATEFROM = createField("hwncell_datefrom", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwncell.hwncell_hwgnodeb</code>.
     */
    public final TableField<HwncellRecord, ULong> HWNCELL_HWGNODEB = createField("hwncell_hwgnodeb", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * The column <code>chrono.hwncell.hwncell_nodealias</code>.
     */
    public final TableField<HwncellRecord, Integer> HWNCELL_NODEALIAS = createField("hwncell_nodealias", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwncell.hwncell_cell</code>.
     */
    public final TableField<HwncellRecord, Integer> HWNCELL_CELL = createField("hwncell_cell", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwncell.hwncell_cellclass</code>.
     */
    public final TableField<HwncellRecord, Integer> HWNCELL_CELLCLASS = createField("hwncell_cellclass", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwncell.hwncell_cellclassgroup</code>.
     */
    public final TableField<HwncellRecord, Integer> HWNCELL_CELLCLASSGROUP = createField("hwncell_cellclassgroup", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwncell.hwncell_cellcoverage</code>.
     */
    public final TableField<HwncellRecord, Integer> HWNCELL_CELLCOVERAGE = createField("hwncell_cellcoverage", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwncell.hwncell_revenueclass</code>.
     */
    public final TableField<HwncellRecord, Integer> HWNCELL_REVENUECLASS = createField("hwncell_revenueclass", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwncell.hwncell_cellstatus</code>.
     */
    public final TableField<HwncellRecord, Integer> HWNCELL_CELLSTATUS = createField("hwncell_cellstatus", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwncell.hwncell_vendor</code>.
     */
    public final TableField<HwncellRecord, Integer> HWNCELL_VENDOR = createField("hwncell_vendor", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwncell.hwncell_latitude</code>.
     */
    public final TableField<HwncellRecord, Double> HWNCELL_LATITUDE = createField("hwncell_latitude", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>chrono.hwncell.hwncell_longitude</code>.
     */
    public final TableField<HwncellRecord, Double> HWNCELL_LONGITUDE = createField("hwncell_longitude", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>chrono.hwncell.hwncell_namingvalid</code>.
     */
    public final TableField<HwncellRecord, Byte> HWNCELL_NAMINGVALID = createField("hwncell_namingvalid", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>chrono.hwncell.CELLID</code>.
     */
    public final TableField<HwncellRecord, String> CELLID = createField("CELLID", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * The column <code>chrono.hwncell.FDN</code>.
     */
    public final TableField<HwncellRecord, String> FDN = createField("FDN", org.jooq.impl.SQLDataType.CHAR(32), this, "");

    /**
     * The column <code>chrono.hwncell.CELLACTIVESTATE</code>.
     */
    public final TableField<HwncellRecord, String> CELLACTIVESTATE = createField("CELLACTIVESTATE", org.jooq.impl.SQLDataType.CHAR(32), this, "");

    /**
     * The column <code>chrono.hwncell.CELLNAME</code>.
     */
    public final TableField<HwncellRecord, String> CELLNAME = createField("CELLNAME", org.jooq.impl.SQLDataType.CHAR(64), this, "");

    /**
     * The column <code>chrono.hwncell.DLNARFCN</code>.
     */
    public final TableField<HwncellRecord, String> DLNARFCN = createField("DLNARFCN", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * The column <code>chrono.hwncell.ULNARFCN</code>.
     */
    public final TableField<HwncellRecord, String> ULNARFCN = createField("ULNARFCN", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * The column <code>chrono.hwncell.DLFREQ</code>.
     */
    public final TableField<HwncellRecord, Double> DLFREQ = createField("DLFREQ", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>chrono.hwncell.ULFREQ</code>.
     */
    public final TableField<HwncellRecord, Double> ULFREQ = createField("ULFREQ", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>chrono.hwncell.GNODEBFUNCTIONNAME</code>.
     */
    public final TableField<HwncellRecord, String> GNODEBFUNCTIONNAME = createField("GNODEBFUNCTIONNAME", org.jooq.impl.SQLDataType.CHAR(96), this, "");

    /**
     * The column <code>chrono.hwncell.DUPLEXMODE</code>.
     */
    public final TableField<HwncellRecord, String> DUPLEXMODE = createField("DUPLEXMODE", org.jooq.impl.SQLDataType.CHAR(12), this, "");

    /**
     * The column <code>chrono.hwncell.LOCALCELLID</code>.
     */
    public final TableField<HwncellRecord, String> LOCALCELLID = createField("LOCALCELLID", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * The column <code>chrono.hwncell.MOINDEX</code>.
     */
    public final TableField<HwncellRecord, String> MOINDEX = createField("MOINDEX", org.jooq.impl.SQLDataType.CHAR(32), this, "");

    /**
     * The column <code>chrono.hwncell.PHYSICALCELLID</code>.
     */
    public final TableField<HwncellRecord, String> PHYSICALCELLID = createField("PHYSICALCELLID", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * The column <code>chrono.hwncell.TXRXMODE</code>.
     */
    public final TableField<HwncellRecord, String> TXRXMODE = createField("TXRXMODE", org.jooq.impl.SQLDataType.CHAR(32), this, "");

    /**
     * The column <code>chrono.hwncell.ULBANDWIDTH</code>.
     */
    public final TableField<HwncellRecord, String> ULBANDWIDTH = createField("ULBANDWIDTH", org.jooq.impl.SQLDataType.CHAR(16), this, "");

    /**
     * The column <code>chrono.hwncell.ULCYCLICPREFIX</code>.
     */
    public final TableField<HwncellRecord, String> ULCYCLICPREFIX = createField("ULCYCLICPREFIX", org.jooq.impl.SQLDataType.CHAR(32), this, "");

    /**
     * The column <code>chrono.hwncell.CNOPERATORNAME</code>.
     */
    public final TableField<HwncellRecord, String> CNOPERATORNAME = createField("CNOPERATORNAME", org.jooq.impl.SQLDataType.CHAR(32), this, "");

    /**
     * The column <code>chrono.hwncell.MCC</code>.
     */
    public final TableField<HwncellRecord, String> MCC = createField("MCC", org.jooq.impl.SQLDataType.CHAR(4), this, "");

    /**
     * The column <code>chrono.hwncell.MNC</code>.
     */
    public final TableField<HwncellRecord, String> MNC = createField("MNC", org.jooq.impl.SQLDataType.CHAR(4), this, "");

    /**
     * The column <code>chrono.hwncell.NBIOTTAFLAG</code>.
     */
    public final TableField<HwncellRecord, String> NBIOTTAFLAG = createField("NBIOTTAFLAG", org.jooq.impl.SQLDataType.CHAR(32), this, "");

    /**
     * The column <code>chrono.hwncell.GNODEBID</code>.
     */
    public final TableField<HwncellRecord, String> GNODEBID = createField("GNODEBID", org.jooq.impl.SQLDataType.CHAR(16), this, "");

    /**
     * The column <code>chrono.hwncell.GGNODEBID</code>.
     */
    public final TableField<HwncellRecord, String> GGNODEBID = createField("GGNODEBID", org.jooq.impl.SQLDataType.CHAR(16), this, "");

    /**
     * The column <code>chrono.hwncell.TAC</code>.
     */
    public final TableField<HwncellRecord, String> TAC = createField("TAC", org.jooq.impl.SQLDataType.CHAR(11), this, "");

    /**
     * The column <code>chrono.hwncell.TAI</code>.
     */
    public final TableField<HwncellRecord, String> TAI = createField("TAI", org.jooq.impl.SQLDataType.CHAR(16), this, "");

    /**
     * The column <code>chrono.hwncell.NCI</code>.
     */
    public final TableField<HwncellRecord, String> NCI = createField("NCI", org.jooq.impl.SQLDataType.CHAR(16), this, "");

    /**
     * The column <code>chrono.hwncell.NCGI</code>.
     */
    public final TableField<HwncellRecord, String> NCGI = createField("NCGI", org.jooq.impl.SQLDataType.CHAR(24), this, "");

    /**
     * The column <code>chrono.hwncell.TRACKINGAREAID</code>.
     */
    public final TableField<HwncellRecord, String> TRACKINGAREAID = createField("TRACKINGAREAID", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * The column <code>chrono.hwncell.LATITUDE</code>.
     */
    public final TableField<HwncellRecord, String> LATITUDE = createField("LATITUDE", org.jooq.impl.SQLDataType.CHAR(16), this, "");

    /**
     * The column <code>chrono.hwncell.LONGITUDE</code>.
     */
    public final TableField<HwncellRecord, String> LONGITUDE = createField("LONGITUDE", org.jooq.impl.SQLDataType.CHAR(16), this, "");

    /**
     * The column <code>chrono.hwncell.hwucell_remark</code>.
     */
    public final TableField<HwncellRecord, String> HWUCELL_REMARK = createField("hwucell_remark", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>chrono.hwncell.DLBANDWIDTH</code>.
     */
    public final TableField<HwncellRecord, String> DLBANDWIDTH = createField("DLBANDWIDTH", org.jooq.impl.SQLDataType.CHAR(16), this, "");

    /**
     * The column <code>chrono.hwncell.FREQUENCYBAND</code>.
     */
    public final TableField<HwncellRecord, String> FREQUENCYBAND = createField("FREQUENCYBAND", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * The column <code>chrono.hwncell.LATITUDEGPS</code>.
     */
    public final TableField<HwncellRecord, String> LATITUDEGPS = createField("LATITUDEGPS", org.jooq.impl.SQLDataType.CHAR(16), this, "");

    /**
     * The column <code>chrono.hwncell.LONGITUDEGPS</code>.
     */
    public final TableField<HwncellRecord, String> LONGITUDEGPS = createField("LONGITUDEGPS", org.jooq.impl.SQLDataType.CHAR(16), this, "");

    /**
     * The column <code>chrono.hwncell.DLCUSTSTARTPRBINDEX</code>.
     */
    public final TableField<HwncellRecord, String> DLCUSTSTARTPRBINDEX = createField("DLCUSTSTARTPRBINDEX", org.jooq.impl.SQLDataType.CHAR(4), this, "");

    /**
     * The column <code>chrono.hwncell.DLCUSTENDPRBINDEX</code>.
     */
    public final TableField<HwncellRecord, String> DLCUSTENDPRBINDEX = createField("DLCUSTENDPRBINDEX", org.jooq.impl.SQLDataType.CHAR(4), this, "");

    /**
     * Create a <code>chrono.hwncell</code> table reference
     */
    public Hwncell() {
        this(DSL.name("hwncell"), null);
    }

    /**
     * Create an aliased <code>chrono.hwncell</code> table reference
     */
    public Hwncell(String alias) {
        this(DSL.name(alias), HWNCELL);
    }

    /**
     * Create an aliased <code>chrono.hwncell</code> table reference
     */
    public Hwncell(Name alias) {
        this(alias, HWNCELL);
    }

    private Hwncell(Name alias, Table<HwncellRecord> aliased) {
        this(alias, aliased, null);
    }

    private Hwncell(Name alias, Table<HwncellRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Chrono.CHRONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<HwncellRecord> getPrimaryKey() {
        return Keys.KEY_HWNCELL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<HwncellRecord>> getKeys() {
        return Arrays.<UniqueKey<HwncellRecord>>asList(Keys.KEY_HWNCELL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Hwncell as(String alias) {
        return new Hwncell(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Hwncell as(Name alias) {
        return new Hwncell(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Hwncell rename(String name) {
        return new Hwncell(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hwncell rename(Name name) {
        return new Hwncell(name, null);
    }
}
