/*
 * This file is generated by jOOQ.
*/
package id.mit.chrono.server.model.tables;


import id.mit.chrono.server.model.Chrono;
import id.mit.chrono.server.model.Indexes;
import id.mit.chrono.server.model.Keys;
import id.mit.chrono.server.model.tables.records.HwucellRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hwucell extends TableImpl<HwucellRecord> {

    private static final long serialVersionUID = 1580125994;

    /**
     * The reference instance of <code>chrono.hwucell</code>
     */
    public static final Hwucell HWUCELL = new Hwucell();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HwucellRecord> getRecordType() {
        return HwucellRecord.class;
    }

    /**
     * The column <code>chrono.hwucell.hwucell_id</code>.
     */
    public final TableField<HwucellRecord, ULong> HWUCELL_ID = createField("hwucell_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>chrono.hwucell.hwucell_crcollectortaskfiles</code>.
     */
    public final TableField<HwucellRecord, ULong> HWUCELL_CRCOLLECTORTASKFILES = createField("hwucell_crcollectortaskfiles", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * The column <code>chrono.hwucell.hwucell_date</code>.
     */
    public final TableField<HwucellRecord, UInteger> HWUCELL_DATE = createField("hwucell_date", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>chrono.hwucell.hwucell_datefrom</code>.
     */
    public final TableField<HwucellRecord, Integer> HWUCELL_DATEFROM = createField("hwucell_datefrom", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwucell.hwucell_hwrnc</code>.
     */
    public final TableField<HwucellRecord, ULong> HWUCELL_HWRNC = createField("hwucell_hwrnc", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * The column <code>chrono.hwucell.hwucell_hwnodeb</code>.
     */
    public final TableField<HwucellRecord, ULong> HWUCELL_HWNODEB = createField("hwucell_hwnodeb", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * The column <code>chrono.hwucell.hwucell_nodealias</code>.
     */
    public final TableField<HwucellRecord, Integer> HWUCELL_NODEALIAS = createField("hwucell_nodealias", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwucell.hwucell_cell</code>.
     */
    public final TableField<HwucellRecord, Integer> HWUCELL_CELL = createField("hwucell_cell", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwucell.hwucell_cellclass</code>.
     */
    public final TableField<HwucellRecord, Integer> HWUCELL_CELLCLASS = createField("hwucell_cellclass", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwucell.hwucell_cellclassgroup</code>.
     */
    public final TableField<HwucellRecord, Integer> HWUCELL_CELLCLASSGROUP = createField("hwucell_cellclassgroup", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwucell.hwucell_cellcoverage</code>.
     */
    public final TableField<HwucellRecord, Integer> HWUCELL_CELLCOVERAGE = createField("hwucell_cellcoverage", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwucell.hwucell_revenueclass</code>.
     */
    public final TableField<HwucellRecord, Integer> HWUCELL_REVENUECLASS = createField("hwucell_revenueclass", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwucell.hwucell_cellstatus</code>.
     */
    public final TableField<HwucellRecord, Integer> HWUCELL_CELLSTATUS = createField("hwucell_cellstatus", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwucell.hwucell_vendor</code>.
     */
    public final TableField<HwucellRecord, Integer> HWUCELL_VENDOR = createField("hwucell_vendor", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwucell.hwucell_latitude</code>.
     */
    public final TableField<HwucellRecord, Double> HWUCELL_LATITUDE = createField("hwucell_latitude", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>chrono.hwucell.hwucell_longitude</code>.
     */
    public final TableField<HwucellRecord, Double> HWUCELL_LONGITUDE = createField("hwucell_longitude", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>chrono.hwucell.hwucell_namingvalid</code>.
     */
    public final TableField<HwucellRecord, Byte> HWUCELL_NAMINGVALID = createField("hwucell_namingvalid", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>chrono.hwucell.CELLNAME</code>.
     */
    public final TableField<HwucellRecord, String> CELLNAME = createField("CELLNAME", org.jooq.impl.SQLDataType.CHAR(96), this, "");

    /**
     * The column <code>chrono.hwucell.CELLID</code>.
     */
    public final TableField<HwucellRecord, String> CELLID = createField("CELLID", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * The column <code>chrono.hwucell.LOGICRNCID</code>.
     */
    public final TableField<HwucellRecord, Integer> LOGICRNCID = createField("LOGICRNCID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwucell.FDN</code>.
     */
    public final TableField<HwucellRecord, String> FDN = createField("FDN", org.jooq.impl.SQLDataType.CHAR(64), this, "");

    /**
     * The column <code>chrono.hwucell.LOCELL</code>.
     */
    public final TableField<HwucellRecord, String> LOCELL = createField("LOCELL", org.jooq.impl.SQLDataType.CHAR(12), this, "");

    /**
     * The column <code>chrono.hwucell.BANDIND</code>.
     */
    public final TableField<HwucellRecord, String> BANDIND = createField("BANDIND", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * The column <code>chrono.hwucell.NODEBNAME</code>.
     */
    public final TableField<HwucellRecord, String> NODEBNAME = createField("NODEBNAME", org.jooq.impl.SQLDataType.CHAR(96), this, "");

    /**
     * The column <code>chrono.hwucell.UARFCNUPLINK</code>.
     */
    public final TableField<HwucellRecord, String> UARFCNUPLINK = createField("UARFCNUPLINK", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * The column <code>chrono.hwucell.UARFCNDOWNLINK</code>.
     */
    public final TableField<HwucellRecord, String> UARFCNDOWNLINK = createField("UARFCNDOWNLINK", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * The column <code>chrono.hwucell.RAC</code>.
     */
    public final TableField<HwucellRecord, String> RAC = createField("RAC", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * The column <code>chrono.hwucell.MAXTXPOWER</code>.
     */
    public final TableField<HwucellRecord, String> MAXTXPOWER = createField("MAXTXPOWER", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * The column <code>chrono.hwucell.PSCRAMBCODE</code>.
     */
    public final TableField<HwucellRecord, String> PSCRAMBCODE = createField("PSCRAMBCODE", org.jooq.impl.SQLDataType.CHAR(16), this, "");

    /**
     * The column <code>chrono.hwucell.MCC</code>.
     */
    public final TableField<HwucellRecord, String> MCC = createField("MCC", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * The column <code>chrono.hwucell.MNC</code>.
     */
    public final TableField<HwucellRecord, String> MNC = createField("MNC", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * The column <code>chrono.hwucell.LAC</code>.
     */
    public final TableField<HwucellRecord, String> LAC = createField("LAC", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * The column <code>chrono.hwucell.CGI</code>.
     */
    public final TableField<HwucellRecord, String> CGI = createField("CGI", org.jooq.impl.SQLDataType.CHAR(32), this, "");

    /**
     * The column <code>chrono.hwucell.SAC</code>.
     */
    public final TableField<HwucellRecord, String> SAC = createField("SAC", org.jooq.impl.SQLDataType.CHAR(32), this, "");

    /**
     * The column <code>chrono.hwucell.ACTSTATUS</code>.
     */
    public final TableField<HwucellRecord, String> ACTSTATUS = createField("ACTSTATUS", org.jooq.impl.SQLDataType.CHAR(24), this, "");

    /**
     * The column <code>chrono.hwucell.BLKSTATUS</code>.
     */
    public final TableField<HwucellRecord, String> BLKSTATUS = createField("BLKSTATUS", org.jooq.impl.SQLDataType.CHAR(24), this, "");

    /**
     * The column <code>chrono.hwucell.MBMSACTFLG</code>.
     */
    public final TableField<HwucellRecord, String> MBMSACTFLG = createField("MBMSACTFLG", org.jooq.impl.SQLDataType.CHAR(24), this, "");

    /**
     * The column <code>chrono.hwucell.MIMOACTFLAG</code>.
     */
    public final TableField<HwucellRecord, String> MIMOACTFLAG = createField("MIMOACTFLAG", org.jooq.impl.SQLDataType.CHAR(24), this, "");

    /**
     * The column <code>chrono.hwucell.MOINDEX</code>.
     */
    public final TableField<HwucellRecord, String> MOINDEX = createField("MOINDEX", org.jooq.impl.SQLDataType.CHAR(24), this, "");

    /**
     * The column <code>chrono.hwucell.NINSYNCIND</code>.
     */
    public final TableField<HwucellRecord, Integer> NINSYNCIND = createField("NINSYNCIND", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwucell.LATITUDE</code>.
     */
    public final TableField<HwucellRecord, String> LATITUDE = createField("LATITUDE", org.jooq.impl.SQLDataType.CHAR(16), this, "");

    /**
     * The column <code>chrono.hwucell.LONGITUDE</code>.
     */
    public final TableField<HwucellRecord, String> LONGITUDE = createField("LONGITUDE", org.jooq.impl.SQLDataType.CHAR(16), this, "");

    /**
     * The column <code>chrono.hwucell.hwucell_remark</code>.
     */
    public final TableField<HwucellRecord, String> HWUCELL_REMARK = createField("hwucell_remark", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>chrono.hwucell.MAXHSDPAUSERNUM</code>.
     */
    public final TableField<HwucellRecord, String> MAXHSDPAUSERNUM = createField("MAXHSDPAUSERNUM", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * The column <code>chrono.hwucell.MAXHSUPAUSERNUM</code>.
     */
    public final TableField<HwucellRecord, String> MAXHSUPAUSERNUM = createField("MAXHSUPAUSERNUM", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * The column <code>chrono.hwucell.EXTPROP1</code>.
     */
    public final TableField<HwucellRecord, Integer> EXTPROP1 = createField("EXTPROP1", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>chrono.hwucell.EXTPROP2</code>.
     */
    public final TableField<HwucellRecord, String> EXTPROP2 = createField("EXTPROP2", org.jooq.impl.SQLDataType.CHAR(8), this, "");

    /**
     * Create a <code>chrono.hwucell</code> table reference
     */
    public Hwucell() {
        this(DSL.name("hwucell"), null);
    }

    /**
     * Create an aliased <code>chrono.hwucell</code> table reference
     */
    public Hwucell(String alias) {
        this(DSL.name(alias), HWUCELL);
    }

    /**
     * Create an aliased <code>chrono.hwucell</code> table reference
     */
    public Hwucell(Name alias) {
        this(alias, HWUCELL);
    }

    private Hwucell(Name alias, Table<HwucellRecord> aliased) {
        this(alias, aliased, null);
    }

    private Hwucell(Name alias, Table<HwucellRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Chrono.CHRONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.HWUCELL_HWBTS_DATE, Indexes.HWUCELL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<HwucellRecord> getPrimaryKey() {
        return Keys.KEY_HWUCELL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<HwucellRecord>> getKeys() {
        return Arrays.<UniqueKey<HwucellRecord>>asList(Keys.KEY_HWUCELL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Hwucell as(String alias) {
        return new Hwucell(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Hwucell as(Name alias) {
        return new Hwucell(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Hwucell rename(String name) {
        return new Hwucell(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hwucell rename(Name name) {
        return new Hwucell(name, null);
    }
}
