/*
 * This file is generated by jOOQ.
*/
package id.mit.chrono.server.model.tables.records;


import id.mit.chrono.server.model.tables.Crcell;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrcellRecord extends UpdatableRecordImpl<CrcellRecord> {

    private static final long serialVersionUID = -871883295;

    /**
     * Setter for <code>chrono.crcell.cell_id</code>.
     */
    public void setCellId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_id</code>.
     */
    public Integer getCellId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>chrono.crcell.cell_antenna</code>.
     */
    public void setCellAntenna(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_antenna</code>.
     */
    public Integer getCellAntenna() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>chrono.crcell.cell_node</code>.
     */
    public void setCellNode(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_node</code>.
     */
    public Integer getCellNode() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>chrono.crcell.cell_site</code>.
     */
    public void setCellSite(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_site</code>.
     */
    public Integer getCellSite() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>chrono.crcell.cell_siteinfo</code>.
     */
    public void setCellSiteinfo(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_siteinfo</code>.
     */
    public String getCellSiteinfo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>chrono.crcell.cell_siteinfo2</code>.
     */
    public void setCellSiteinfo2(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_siteinfo2</code>.
     */
    public String getCellSiteinfo2() {
        return (String) get(5);
    }

    /**
     * Setter for <code>chrono.crcell.cell_siteinfolatitude</code>.
     */
    public void setCellSiteinfolatitude(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_siteinfolatitude</code>.
     */
    public Double getCellSiteinfolatitude() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>chrono.crcell.cell_siteinfolongitude</code>.
     */
    public void setCellSiteinfolongitude(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_siteinfolongitude</code>.
     */
    public Double getCellSiteinfolongitude() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>chrono.crcell.cell_cellclass</code>.
     */
    public void setCellCellclass(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_cellclass</code>.
     */
    public Integer getCellCellclass() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>chrono.crcell.cell_cellcoverage</code>.
     */
    public void setCellCellcoverage(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_cellcoverage</code>.
     */
    public Integer getCellCellcoverage() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>chrono.crcell.cell_revenueclass</code>.
     */
    public void setCellRevenueclass(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_revenueclass</code>.
     */
    public Integer getCellRevenueclass() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>chrono.crcell.cell_namingvalid</code>.
     */
    public void setCellNamingvalid(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_namingvalid</code>.
     */
    public Byte getCellNamingvalid() {
        return (Byte) get(11);
    }

    /**
     * Setter for <code>chrono.crcell.cell_cgi</code>.
     */
    public void setCellCgi(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_cgi</code>.
     */
    public String getCellCgi() {
        return (String) get(12);
    }

    /**
     * Setter for <code>chrono.crcell.cell_ecgi</code>.
     */
    public void setCellEcgi(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_ecgi</code>.
     */
    public String getCellEcgi() {
        return (String) get(13);
    }

    /**
     * Setter for <code>chrono.crcell.cell_mcc</code>.
     */
    public void setCellMcc(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_mcc</code>.
     */
    public Integer getCellMcc() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>chrono.crcell.cell_mnc</code>.
     */
    public void setCellMnc(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_mnc</code>.
     */
    public Integer getCellMnc() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>chrono.crcell.cell_lac</code>.
     */
    public void setCellLac(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_lac</code>.
     */
    public Integer getCellLac() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>chrono.crcell.cell_tac</code>.
     */
    public void setCellTac(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_tac</code>.
     */
    public Integer getCellTac() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>chrono.crcell.cell_ci</code>.
     */
    public void setCellCi(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_ci</code>.
     */
    public Integer getCellCi() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>chrono.crcell.cell_pci</code>.
     */
    public void setCellPci(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_pci</code>.
     */
    public Integer getCellPci() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>chrono.crcell.cell_bsic</code>.
     */
    public void setCellBsic(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_bsic</code>.
     */
    public Integer getCellBsic() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>chrono.crcell.cell_rncid</code>.
     */
    public void setCellRncid(Integer value) {
        set(21, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_rncid</code>.
     */
    public Integer getCellRncid() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>chrono.crcell.cell_enbid</code>.
     */
    public void setCellEnbid(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_enbid</code>.
     */
    public Integer getCellEnbid() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>chrono.crcell.cell_sac</code>.
     */
    public void setCellSac(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_sac</code>.
     */
    public Integer getCellSac() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>chrono.crcell.cell_rac</code>.
     */
    public void setCellRac(Integer value) {
        set(24, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_rac</code>.
     */
    public Integer getCellRac() {
        return (Integer) get(24);
    }

    /**
     * Setter for <code>chrono.crcell.cell_psc</code>.
     */
    public void setCellPsc(Integer value) {
        set(25, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_psc</code>.
     */
    public Integer getCellPsc() {
        return (Integer) get(25);
    }

    /**
     * Setter for <code>chrono.crcell.cell_uluarfcn</code>.
     */
    public void setCellUluarfcn(Integer value) {
        set(26, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_uluarfcn</code>.
     */
    public Integer getCellUluarfcn() {
        return (Integer) get(26);
    }

    /**
     * Setter for <code>chrono.crcell.cell_dluarfcn</code>.
     */
    public void setCellDluarfcn(Integer value) {
        set(27, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_dluarfcn</code>.
     */
    public Integer getCellDluarfcn() {
        return (Integer) get(27);
    }

    /**
     * Setter for <code>chrono.crcell.cell_latitude</code>.
     */
    public void setCellLatitude(Double value) {
        set(28, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_latitude</code>.
     */
    public Double getCellLatitude() {
        return (Double) get(28);
    }

    /**
     * Setter for <code>chrono.crcell.cell_longitude</code>.
     */
    public void setCellLongitude(Double value) {
        set(29, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_longitude</code>.
     */
    public Double getCellLongitude() {
        return (Double) get(29);
    }

    /**
     * Setter for <code>chrono.crcell.cell_direction</code>.
     */
    public void setCellDirection(Integer value) {
        set(30, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_direction</code>.
     */
    public Integer getCellDirection() {
        return (Integer) get(30);
    }

    /**
     * Setter for <code>chrono.crcell.cell_lastupdate</code>.
     */
    public void setCellLastupdate(Integer value) {
        set(31, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_lastupdate</code>.
     */
    public Integer getCellLastupdate() {
        return (Integer) get(31);
    }

    /**
     * Setter for <code>chrono.crcell.cell_validationtime</code>.
     */
    public void setCellValidationtime(Integer value) {
        set(32, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_validationtime</code>.
     */
    public Integer getCellValidationtime() {
        return (Integer) get(32);
    }

    /**
     * Setter for <code>chrono.crcell.cell_validationnote</code>.
     */
    public void setCellValidationnote(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_validationnote</code>.
     */
    public String getCellValidationnote() {
        return (String) get(33);
    }

    /**
     * Setter for <code>chrono.crcell.cell_verificator</code>.
     */
    public void setCellVerificator(Integer value) {
        set(34, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_verificator</code>.
     */
    public Integer getCellVerificator() {
        return (Integer) get(34);
    }

    /**
     * Setter for <code>chrono.crcell.cell_verificationnote</code>.
     */
    public void setCellVerificationnote(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_verificationnote</code>.
     */
    public String getCellVerificationnote() {
        return (String) get(35);
    }

    /**
     * Setter for <code>chrono.crcell.cell_ncgi</code>.
     */
    public void setCellNcgi(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>chrono.crcell.cell_ncgi</code>.
     */
    public String getCellNcgi() {
        return (String) get(36);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CrcellRecord
     */
    public CrcellRecord() {
        super(Crcell.CRCELL);
    }

    /**
     * Create a detached, initialised CrcellRecord
     */
    public CrcellRecord(Integer cellId, Integer cellAntenna, Integer cellNode, Integer cellSite, String cellSiteinfo, String cellSiteinfo2, Double cellSiteinfolatitude, Double cellSiteinfolongitude, Integer cellCellclass, Integer cellCellcoverage, Integer cellRevenueclass, Byte cellNamingvalid, String cellCgi, String cellEcgi, Integer cellMcc, Integer cellMnc, Integer cellLac, Integer cellTac, Integer cellCi, Integer cellPci, Integer cellBsic, Integer cellRncid, Integer cellEnbid, Integer cellSac, Integer cellRac, Integer cellPsc, Integer cellUluarfcn, Integer cellDluarfcn, Double cellLatitude, Double cellLongitude, Integer cellDirection, Integer cellLastupdate, Integer cellValidationtime, String cellValidationnote, Integer cellVerificator, String cellVerificationnote, String cellNcgi) {
        super(Crcell.CRCELL);

        set(0, cellId);
        set(1, cellAntenna);
        set(2, cellNode);
        set(3, cellSite);
        set(4, cellSiteinfo);
        set(5, cellSiteinfo2);
        set(6, cellSiteinfolatitude);
        set(7, cellSiteinfolongitude);
        set(8, cellCellclass);
        set(9, cellCellcoverage);
        set(10, cellRevenueclass);
        set(11, cellNamingvalid);
        set(12, cellCgi);
        set(13, cellEcgi);
        set(14, cellMcc);
        set(15, cellMnc);
        set(16, cellLac);
        set(17, cellTac);
        set(18, cellCi);
        set(19, cellPci);
        set(20, cellBsic);
        set(21, cellRncid);
        set(22, cellEnbid);
        set(23, cellSac);
        set(24, cellRac);
        set(25, cellPsc);
        set(26, cellUluarfcn);
        set(27, cellDluarfcn);
        set(28, cellLatitude);
        set(29, cellLongitude);
        set(30, cellDirection);
        set(31, cellLastupdate);
        set(32, cellValidationtime);
        set(33, cellValidationnote);
        set(34, cellVerificator);
        set(35, cellVerificationnote);
        set(36, cellNcgi);
    }
}
