/*
 * This file is generated by jOOQ.
*/
package id.mit.chrono.server.model.tables.records;


import id.mit.chrono.server.model.tables.Crcompany;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrcompanyRecord extends UpdatableRecordImpl<CrcompanyRecord> implements Record8<Integer, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -747017699;

    /**
     * Setter for <code>chrono.crcompany.company_id</code>.
     */
    public void setCompanyId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>chrono.crcompany.company_id</code>.
     */
    public Integer getCompanyId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>chrono.crcompany.company_code</code>.
     */
    public void setCompanyCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>chrono.crcompany.company_code</code>.
     */
    public String getCompanyCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>chrono.crcompany.company_name</code>.
     */
    public void setCompanyName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>chrono.crcompany.company_name</code>.
     */
    public String getCompanyName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>chrono.crcompany.company_address</code>.
     */
    public void setCompanyAddress(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>chrono.crcompany.company_address</code>.
     */
    public String getCompanyAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>chrono.crcompany.company_postalcode</code>.
     */
    public void setCompanyPostalcode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>chrono.crcompany.company_postalcode</code>.
     */
    public String getCompanyPostalcode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>chrono.crcompany.company_phone</code>.
     */
    public void setCompanyPhone(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>chrono.crcompany.company_phone</code>.
     */
    public String getCompanyPhone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>chrono.crcompany.company_fax</code>.
     */
    public void setCompanyFax(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>chrono.crcompany.company_fax</code>.
     */
    public String getCompanyFax() {
        return (String) get(6);
    }

    /**
     * Setter for <code>chrono.crcompany.company_website</code>.
     */
    public void setCompanyWebsite(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>chrono.crcompany.company_website</code>.
     */
    public String getCompanyWebsite() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, String, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Crcompany.CRCOMPANY.COMPANY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Crcompany.CRCOMPANY.COMPANY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Crcompany.CRCOMPANY.COMPANY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Crcompany.CRCOMPANY.COMPANY_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Crcompany.CRCOMPANY.COMPANY_POSTALCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Crcompany.CRCOMPANY.COMPANY_PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Crcompany.CRCOMPANY.COMPANY_FAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Crcompany.CRCOMPANY.COMPANY_WEBSITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCompanyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCompanyAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCompanyPostalcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCompanyPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getCompanyFax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCompanyWebsite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCompanyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCompanyAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCompanyPostalcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCompanyPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCompanyFax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCompanyWebsite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrcompanyRecord value1(Integer value) {
        setCompanyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrcompanyRecord value2(String value) {
        setCompanyCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrcompanyRecord value3(String value) {
        setCompanyName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrcompanyRecord value4(String value) {
        setCompanyAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrcompanyRecord value5(String value) {
        setCompanyPostalcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrcompanyRecord value6(String value) {
        setCompanyPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrcompanyRecord value7(String value) {
        setCompanyFax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrcompanyRecord value8(String value) {
        setCompanyWebsite(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrcompanyRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CrcompanyRecord
     */
    public CrcompanyRecord() {
        super(Crcompany.CRCOMPANY);
    }

    /**
     * Create a detached, initialised CrcompanyRecord
     */
    public CrcompanyRecord(Integer companyId, String companyCode, String companyName, String companyAddress, String companyPostalcode, String companyPhone, String companyFax, String companyWebsite) {
        super(Crcompany.CRCOMPANY);

        set(0, companyId);
        set(1, companyCode);
        set(2, companyName);
        set(3, companyAddress);
        set(4, companyPostalcode);
        set(5, companyPhone);
        set(6, companyFax);
        set(7, companyWebsite);
    }
}
