/*
 * This file is generated by jOOQ.
*/
package id.mit.chrono.server.model.tables.records;


import id.mit.chrono.server.model.tables.Crsettings;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrsettingsRecord extends UpdatableRecordImpl<CrsettingsRecord> implements Record7<Integer, String, String, Integer, String, String, Byte> {

    private static final long serialVersionUID = 656472465;

    /**
     * Setter for <code>chrono.crsettings.settings_id</code>.
     */
    public void setSettingsId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>chrono.crsettings.settings_id</code>.
     */
    public Integer getSettingsId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>chrono.crsettings.settings_code</code>.
     */
    public void setSettingsCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>chrono.crsettings.settings_code</code>.
     */
    public String getSettingsCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>chrono.crsettings.settings_name</code>.
     */
    public void setSettingsName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>chrono.crsettings.settings_name</code>.
     */
    public String getSettingsName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>chrono.crsettings.settings_order</code>.
     */
    public void setSettingsOrder(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>chrono.crsettings.settings_order</code>.
     */
    public Integer getSettingsOrder() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>chrono.crsettings.settings_description</code>.
     */
    public void setSettingsDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>chrono.crsettings.settings_description</code>.
     */
    public String getSettingsDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>chrono.crsettings.settings_value</code>.
     */
    public void setSettingsValue(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>chrono.crsettings.settings_value</code>.
     */
    public String getSettingsValue() {
        return (String) get(5);
    }

    /**
     * Setter for <code>chrono.crsettings.settings_enabled</code>.
     */
    public void setSettingsEnabled(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>chrono.crsettings.settings_enabled</code>.
     */
    public Byte getSettingsEnabled() {
        return (Byte) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Integer, String, String, Byte> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Integer, String, String, Byte> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Crsettings.CRSETTINGS.SETTINGS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Crsettings.CRSETTINGS.SETTINGS_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Crsettings.CRSETTINGS.SETTINGS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Crsettings.CRSETTINGS.SETTINGS_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Crsettings.CRSETTINGS.SETTINGS_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Crsettings.CRSETTINGS.SETTINGS_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return Crsettings.CRSETTINGS.SETTINGS_ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getSettingsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSettingsCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSettingsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getSettingsOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSettingsDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSettingsValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getSettingsEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSettingsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSettingsCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSettingsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getSettingsOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSettingsDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSettingsValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getSettingsEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrsettingsRecord value1(Integer value) {
        setSettingsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrsettingsRecord value2(String value) {
        setSettingsCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrsettingsRecord value3(String value) {
        setSettingsName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrsettingsRecord value4(Integer value) {
        setSettingsOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrsettingsRecord value5(String value) {
        setSettingsDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrsettingsRecord value6(String value) {
        setSettingsValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrsettingsRecord value7(Byte value) {
        setSettingsEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrsettingsRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, Byte value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CrsettingsRecord
     */
    public CrsettingsRecord() {
        super(Crsettings.CRSETTINGS);
    }

    /**
     * Create a detached, initialised CrsettingsRecord
     */
    public CrsettingsRecord(Integer settingsId, String settingsCode, String settingsName, Integer settingsOrder, String settingsDescription, String settingsValue, Byte settingsEnabled) {
        super(Crsettings.CRSETTINGS);

        set(0, settingsId);
        set(1, settingsCode);
        set(2, settingsName);
        set(3, settingsOrder);
        set(4, settingsDescription);
        set(5, settingsValue);
        set(6, settingsEnabled);
    }
}
