/*
 * This file is generated by jOOQ.
*/
package id.mit.chrono.server.model.tables.records;


import id.mit.chrono.server.model.tables.Crsiteprefix;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrsiteprefixRecord extends UpdatableRecordImpl<CrsiteprefixRecord> implements Record4<Integer, Integer, String, Integer> {

    private static final long serialVersionUID = 644657639;

    /**
     * Setter for <code>chrono.crsiteprefix.siteprefix_id</code>.
     */
    public void setSiteprefixId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>chrono.crsiteprefix.siteprefix_id</code>.
     */
    public Integer getSiteprefixId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>chrono.crsiteprefix.siteprefix_site</code>.
     */
    public void setSiteprefixSite(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>chrono.crsiteprefix.siteprefix_site</code>.
     */
    public Integer getSiteprefixSite() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>chrono.crsiteprefix.siteprefix_prefix</code>.
     */
    public void setSiteprefixPrefix(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>chrono.crsiteprefix.siteprefix_prefix</code>.
     */
    public String getSiteprefixPrefix() {
        return (String) get(2);
    }

    /**
     * Setter for <code>chrono.crsiteprefix.siteprefix_sitearea</code>.
     */
    public void setSiteprefixSitearea(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>chrono.crsiteprefix.siteprefix_sitearea</code>.
     */
    public Integer getSiteprefixSitearea() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Crsiteprefix.CRSITEPREFIX.SITEPREFIX_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Crsiteprefix.CRSITEPREFIX.SITEPREFIX_SITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Crsiteprefix.CRSITEPREFIX.SITEPREFIX_PREFIX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Crsiteprefix.CRSITEPREFIX.SITEPREFIX_SITEAREA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getSiteprefixId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSiteprefixSite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSiteprefixPrefix();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getSiteprefixSitearea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSiteprefixId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSiteprefixSite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSiteprefixPrefix();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getSiteprefixSitearea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrsiteprefixRecord value1(Integer value) {
        setSiteprefixId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrsiteprefixRecord value2(Integer value) {
        setSiteprefixSite(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrsiteprefixRecord value3(String value) {
        setSiteprefixPrefix(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrsiteprefixRecord value4(Integer value) {
        setSiteprefixSitearea(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrsiteprefixRecord values(Integer value1, Integer value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CrsiteprefixRecord
     */
    public CrsiteprefixRecord() {
        super(Crsiteprefix.CRSITEPREFIX);
    }

    /**
     * Create a detached, initialised CrsiteprefixRecord
     */
    public CrsiteprefixRecord(Integer siteprefixId, Integer siteprefixSite, String siteprefixPrefix, Integer siteprefixSitearea) {
        super(Crsiteprefix.CRSITEPREFIX);

        set(0, siteprefixId);
        set(1, siteprefixSite);
        set(2, siteprefixPrefix);
        set(3, siteprefixSitearea);
    }
}
