/*
 * This file is generated by jOOQ.
*/
package id.mit.chrono.server.model.tables.records;


import id.mit.chrono.server.model.tables.Crtimecatalog;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrtimecatalogRecord extends UpdatableRecordImpl<CrtimecatalogRecord> implements Record5<Integer, Integer, Integer, Byte, Byte> {

    private static final long serialVersionUID = -1105745092;

    /**
     * Setter for <code>chrono.crtimecatalog.timecatalog_id</code>.
     */
    public void setTimecatalogId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>chrono.crtimecatalog.timecatalog_id</code>.
     */
    public Integer getTimecatalogId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>chrono.crtimecatalog.timecatalog_datagroup</code>.
     */
    public void setTimecatalogDatagroup(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>chrono.crtimecatalog.timecatalog_datagroup</code>.
     */
    public Integer getTimecatalogDatagroup() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>chrono.crtimecatalog.timecatalog_date</code>.
     */
    public void setTimecatalogDate(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>chrono.crtimecatalog.timecatalog_date</code>.
     */
    public Integer getTimecatalogDate() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>chrono.crtimecatalog.timecatalog_active</code>.
     */
    public void setTimecatalogActive(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>chrono.crtimecatalog.timecatalog_active</code>.
     */
    public Byte getTimecatalogActive() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>chrono.crtimecatalog.timecatalog_adminonly</code>.
     */
    public void setTimecatalogAdminonly(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>chrono.crtimecatalog.timecatalog_adminonly</code>.
     */
    public Byte getTimecatalogAdminonly() {
        return (Byte) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Byte, Byte> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Byte, Byte> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Crtimecatalog.CRTIMECATALOG.TIMECATALOG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Crtimecatalog.CRTIMECATALOG.TIMECATALOG_DATAGROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Crtimecatalog.CRTIMECATALOG.TIMECATALOG_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return Crtimecatalog.CRTIMECATALOG.TIMECATALOG_ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return Crtimecatalog.CRTIMECATALOG.TIMECATALOG_ADMINONLY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getTimecatalogId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getTimecatalogDatagroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getTimecatalogDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getTimecatalogActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getTimecatalogAdminonly();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getTimecatalogId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTimecatalogDatagroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTimecatalogDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getTimecatalogActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getTimecatalogAdminonly();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrtimecatalogRecord value1(Integer value) {
        setTimecatalogId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrtimecatalogRecord value2(Integer value) {
        setTimecatalogDatagroup(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrtimecatalogRecord value3(Integer value) {
        setTimecatalogDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrtimecatalogRecord value4(Byte value) {
        setTimecatalogActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrtimecatalogRecord value5(Byte value) {
        setTimecatalogAdminonly(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrtimecatalogRecord values(Integer value1, Integer value2, Integer value3, Byte value4, Byte value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CrtimecatalogRecord
     */
    public CrtimecatalogRecord() {
        super(Crtimecatalog.CRTIMECATALOG);
    }

    /**
     * Create a detached, initialised CrtimecatalogRecord
     */
    public CrtimecatalogRecord(Integer timecatalogId, Integer timecatalogDatagroup, Integer timecatalogDate, Byte timecatalogActive, Byte timecatalogAdminonly) {
        super(Crtimecatalog.CRTIMECATALOG);

        set(0, timecatalogId);
        set(1, timecatalogDatagroup);
        set(2, timecatalogDate);
        set(3, timecatalogActive);
        set(4, timecatalogAdminonly);
    }
}
