/*
 * This file is generated by jOOQ.
*/
package id.mit.chrono.server.model.tables.records;


import id.mit.chrono.server.model.tables.Crworkflow;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrworkflowRecord extends UpdatableRecordImpl<CrworkflowRecord> implements Record14<Integer, String, Integer, Integer, Integer, String, String, Integer, String, String, String, String, String, Byte> {

    private static final long serialVersionUID = -1016254560;

    /**
     * Setter for <code>chrono.crworkflow.workflow_id</code>.
     */
    public void setWorkflowId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>chrono.crworkflow.workflow_id</code>.
     */
    public Integer getWorkflowId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>chrono.crworkflow.workflow_code</code>.
     */
    public void setWorkflowCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>chrono.crworkflow.workflow_code</code>.
     */
    public String getWorkflowCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>chrono.crworkflow.workflow_vendor</code>.
     */
    public void setWorkflowVendor(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>chrono.crworkflow.workflow_vendor</code>.
     */
    public Integer getWorkflowVendor() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>chrono.crworkflow.workflow_datagroup</code>.
     */
    public void setWorkflowDatagroup(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>chrono.crworkflow.workflow_datagroup</code>.
     */
    public Integer getWorkflowDatagroup() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>chrono.crworkflow.workflow_datasourcetype</code>.
     */
    public void setWorkflowDatasourcetype(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>chrono.crworkflow.workflow_datasourcetype</code>.
     */
    public Integer getWorkflowDatasourcetype() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>chrono.crworkflow.workflow_entitygroup</code>.
     */
    public void setWorkflowEntitygroup(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>chrono.crworkflow.workflow_entitygroup</code>.
     */
    public String getWorkflowEntitygroup() {
        return (String) get(5);
    }

    /**
     * Setter for <code>chrono.crworkflow.workflow_entity</code>.
     */
    public void setWorkflowEntity(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>chrono.crworkflow.workflow_entity</code>.
     */
    public String getWorkflowEntity() {
        return (String) get(6);
    }

    /**
     * Setter for <code>chrono.crworkflow.workflow_phase</code>.
     */
    public void setWorkflowPhase(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>chrono.crworkflow.workflow_phase</code>.
     */
    public Integer getWorkflowPhase() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>chrono.crworkflow.workflow_identitypattern</code>.
     */
    public void setWorkflowIdentitypattern(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>chrono.crworkflow.workflow_identitypattern</code>.
     */
    public String getWorkflowIdentitypattern() {
        return (String) get(8);
    }

    /**
     * Setter for <code>chrono.crworkflow.workflow_dependencies</code>.
     */
    public void setWorkflowDependencies(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>chrono.crworkflow.workflow_dependencies</code>.
     */
    public String getWorkflowDependencies() {
        return (String) get(9);
    }

    /**
     * Setter for <code>chrono.crworkflow.workflow_localdir</code>.
     */
    public void setWorkflowLocaldir(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>chrono.crworkflow.workflow_localdir</code>.
     */
    public String getWorkflowLocaldir() {
        return (String) get(10);
    }

    /**
     * Setter for <code>chrono.crworkflow.workflow_class</code>.
     */
    public void setWorkflowClass(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>chrono.crworkflow.workflow_class</code>.
     */
    public String getWorkflowClass() {
        return (String) get(11);
    }

    /**
     * Setter for <code>chrono.crworkflow.workflow_description</code>.
     */
    public void setWorkflowDescription(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>chrono.crworkflow.workflow_description</code>.
     */
    public String getWorkflowDescription() {
        return (String) get(12);
    }

    /**
     * Setter for <code>chrono.crworkflow.workflow_enabled</code>.
     */
    public void setWorkflowEnabled(Byte value) {
        set(13, value);
    }

    /**
     * Getter for <code>chrono.crworkflow.workflow_enabled</code>.
     */
    public Byte getWorkflowEnabled() {
        return (Byte) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, String, Integer, Integer, Integer, String, String, Integer, String, String, String, String, String, Byte> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, String, Integer, Integer, Integer, String, String, Integer, String, String, String, String, String, Byte> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Crworkflow.CRWORKFLOW.WORKFLOW_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Crworkflow.CRWORKFLOW.WORKFLOW_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Crworkflow.CRWORKFLOW.WORKFLOW_VENDOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Crworkflow.CRWORKFLOW.WORKFLOW_DATAGROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Crworkflow.CRWORKFLOW.WORKFLOW_DATASOURCETYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Crworkflow.CRWORKFLOW.WORKFLOW_ENTITYGROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Crworkflow.CRWORKFLOW.WORKFLOW_ENTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Crworkflow.CRWORKFLOW.WORKFLOW_PHASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Crworkflow.CRWORKFLOW.WORKFLOW_IDENTITYPATTERN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Crworkflow.CRWORKFLOW.WORKFLOW_DEPENDENCIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Crworkflow.CRWORKFLOW.WORKFLOW_LOCALDIR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Crworkflow.CRWORKFLOW.WORKFLOW_CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Crworkflow.CRWORKFLOW.WORKFLOW_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field14() {
        return Crworkflow.CRWORKFLOW.WORKFLOW_ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getWorkflowId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getWorkflowCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getWorkflowVendor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getWorkflowDatagroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getWorkflowDatasourcetype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getWorkflowEntitygroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getWorkflowEntity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getWorkflowPhase();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getWorkflowIdentitypattern();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getWorkflowDependencies();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getWorkflowLocaldir();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getWorkflowClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getWorkflowDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component14() {
        return getWorkflowEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getWorkflowId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getWorkflowCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getWorkflowVendor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getWorkflowDatagroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getWorkflowDatasourcetype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getWorkflowEntitygroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getWorkflowEntity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getWorkflowPhase();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getWorkflowIdentitypattern();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getWorkflowDependencies();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getWorkflowLocaldir();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getWorkflowClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getWorkflowDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value14() {
        return getWorkflowEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrworkflowRecord value1(Integer value) {
        setWorkflowId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrworkflowRecord value2(String value) {
        setWorkflowCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrworkflowRecord value3(Integer value) {
        setWorkflowVendor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrworkflowRecord value4(Integer value) {
        setWorkflowDatagroup(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrworkflowRecord value5(Integer value) {
        setWorkflowDatasourcetype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrworkflowRecord value6(String value) {
        setWorkflowEntitygroup(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrworkflowRecord value7(String value) {
        setWorkflowEntity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrworkflowRecord value8(Integer value) {
        setWorkflowPhase(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrworkflowRecord value9(String value) {
        setWorkflowIdentitypattern(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrworkflowRecord value10(String value) {
        setWorkflowDependencies(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrworkflowRecord value11(String value) {
        setWorkflowLocaldir(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrworkflowRecord value12(String value) {
        setWorkflowClass(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrworkflowRecord value13(String value) {
        setWorkflowDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrworkflowRecord value14(Byte value) {
        setWorkflowEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrworkflowRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, String value6, String value7, Integer value8, String value9, String value10, String value11, String value12, String value13, Byte value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CrworkflowRecord
     */
    public CrworkflowRecord() {
        super(Crworkflow.CRWORKFLOW);
    }

    /**
     * Create a detached, initialised CrworkflowRecord
     */
    public CrworkflowRecord(Integer workflowId, String workflowCode, Integer workflowVendor, Integer workflowDatagroup, Integer workflowDatasourcetype, String workflowEntitygroup, String workflowEntity, Integer workflowPhase, String workflowIdentitypattern, String workflowDependencies, String workflowLocaldir, String workflowClass, String workflowDescription, Byte workflowEnabled) {
        super(Crworkflow.CRWORKFLOW);

        set(0, workflowId);
        set(1, workflowCode);
        set(2, workflowVendor);
        set(3, workflowDatagroup);
        set(4, workflowDatasourcetype);
        set(5, workflowEntitygroup);
        set(6, workflowEntity);
        set(7, workflowPhase);
        set(8, workflowIdentitypattern);
        set(9, workflowDependencies);
        set(10, workflowLocaldir);
        set(11, workflowClass);
        set(12, workflowDescription);
        set(13, workflowEnabled);
    }
}
