/*
 * This file is generated by jOOQ.
*/
package id.mit.chrono.server.model.tables.records;


import id.mit.chrono.server.model.tables.Erbts;

import javax.annotation.Generated;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ErbtsRecord extends UpdatableRecordImpl<ErbtsRecord> {

    private static final long serialVersionUID = -1877685457;

    /**
     * Setter for <code>chrono.erbts.erbts_id</code>.
     */
    public void setErbtsId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>chrono.erbts.erbts_id</code>.
     */
    public ULong getErbtsId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>chrono.erbts.erbts_crcollectortaskfiles</code>.
     */
    public void setErbtsCrcollectortaskfiles(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>chrono.erbts.erbts_crcollectortaskfiles</code>.
     */
    public ULong getErbtsCrcollectortaskfiles() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>chrono.erbts.erbts_date</code>.
     */
    public void setErbtsDate(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>chrono.erbts.erbts_date</code>.
     */
    public UInteger getErbtsDate() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>chrono.erbts.erbts_datefrom</code>.
     */
    public void setErbtsDatefrom(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>chrono.erbts.erbts_datefrom</code>.
     */
    public Integer getErbtsDatefrom() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>chrono.erbts.erbts_erbsc</code>.
     */
    public void setErbtsErbsc(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>chrono.erbts.erbts_erbsc</code>.
     */
    public ULong getErbtsErbsc() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>chrono.erbts.erbts_node</code>.
     */
    public void setErbtsNode(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>chrono.erbts.erbts_node</code>.
     */
    public Integer getErbtsNode() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>chrono.erbts.erbts_nodephysical</code>.
     */
    public void setErbtsNodephysical(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>chrono.erbts.erbts_nodephysical</code>.
     */
    public Integer getErbtsNodephysical() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>chrono.erbts.erbts_nodestatus</code>.
     */
    public void setErbtsNodestatus(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>chrono.erbts.erbts_nodestatus</code>.
     */
    public Integer getErbtsNodestatus() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>chrono.erbts.erbts_revenueclass</code>.
     */
    public void setErbtsRevenueclass(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>chrono.erbts.erbts_revenueclass</code>.
     */
    public Integer getErbtsRevenueclass() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>chrono.erbts.erbts_vendor</code>.
     */
    public void setErbtsVendor(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>chrono.erbts.erbts_vendor</code>.
     */
    public Integer getErbtsVendor() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>chrono.erbts.erbts_namingvalid</code>.
     */
    public void setErbtsNamingvalid(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>chrono.erbts.erbts_namingvalid</code>.
     */
    public Byte getErbtsNamingvalid() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>chrono.erbts.TOTALCELL</code>.
     */
    public void setTotalcell(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>chrono.erbts.TOTALCELL</code>.
     */
    public Integer getTotalcell() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>chrono.erbts.TOTALTRX</code>.
     */
    public void setTotaltrx(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>chrono.erbts.TOTALTRX</code>.
     */
    public Integer getTotaltrx() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>chrono.erbts.BTSNAME</code>.
     */
    public void setBtsname(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>chrono.erbts.BTSNAME</code>.
     */
    public String getBtsname() {
        return (String) get(13);
    }

    /**
     * Setter for <code>chrono.erbts.BTSID</code>.
     */
    public void setBtsid(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>chrono.erbts.BTSID</code>.
     */
    public Integer getBtsid() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>chrono.erbts.TG</code>.
     */
    public void setTg(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>chrono.erbts.TG</code>.
     */
    public String getTg() {
        return (String) get(15);
    }

    /**
     * Setter for <code>chrono.erbts.SITE</code>.
     */
    public void setSite(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>chrono.erbts.SITE</code>.
     */
    public String getSite() {
        return (String) get(16);
    }

    /**
     * Setter for <code>chrono.erbts.NEID</code>.
     */
    public void setNeid(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>chrono.erbts.NEID</code>.
     */
    public String getNeid() {
        return (String) get(17);
    }

    /**
     * Setter for <code>chrono.erbts.LATITUDE</code>.
     */
    public void setLatitude(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>chrono.erbts.LATITUDE</code>.
     */
    public String getLatitude() {
        return (String) get(18);
    }

    /**
     * Setter for <code>chrono.erbts.LONGITUDE</code>.
     */
    public void setLongitude(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>chrono.erbts.LONGITUDE</code>.
     */
    public String getLongitude() {
        return (String) get(19);
    }

    /**
     * Setter for <code>chrono.erbts.SWVERSION</code>.
     */
    public void setSwversion(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>chrono.erbts.SWVERSION</code>.
     */
    public String getSwversion() {
        return (String) get(20);
    }

    /**
     * Setter for <code>chrono.erbts.erbts_remark</code>.
     */
    public void setErbtsRemark(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>chrono.erbts.erbts_remark</code>.
     */
    public String getErbtsRemark() {
        return (String) get(21);
    }

    /**
     * Setter for <code>chrono.erbts.EXTPROP1</code>.
     */
    public void setExtprop1(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>chrono.erbts.EXTPROP1</code>.
     */
    public Integer getExtprop1() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>chrono.erbts.EXTPROP2</code>.
     */
    public void setExtprop2(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>chrono.erbts.EXTPROP2</code>.
     */
    public String getExtprop2() {
        return (String) get(23);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<ULong, ULong> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ErbtsRecord
     */
    public ErbtsRecord() {
        super(Erbts.ERBTS);
    }

    /**
     * Create a detached, initialised ErbtsRecord
     */
    public ErbtsRecord(ULong erbtsId, ULong erbtsCrcollectortaskfiles, UInteger erbtsDate, Integer erbtsDatefrom, ULong erbtsErbsc, Integer erbtsNode, Integer erbtsNodephysical, Integer erbtsNodestatus, Integer erbtsRevenueclass, Integer erbtsVendor, Byte erbtsNamingvalid, Integer totalcell, Integer totaltrx, String btsname, Integer btsid, String tg, String site, String neid, String latitude, String longitude, String swversion, String erbtsRemark, Integer extprop1, String extprop2) {
        super(Erbts.ERBTS);

        set(0, erbtsId);
        set(1, erbtsCrcollectortaskfiles);
        set(2, erbtsDate);
        set(3, erbtsDatefrom);
        set(4, erbtsErbsc);
        set(5, erbtsNode);
        set(6, erbtsNodephysical);
        set(7, erbtsNodestatus);
        set(8, erbtsRevenueclass);
        set(9, erbtsVendor);
        set(10, erbtsNamingvalid);
        set(11, totalcell);
        set(12, totaltrx);
        set(13, btsname);
        set(14, btsid);
        set(15, tg);
        set(16, site);
        set(17, neid);
        set(18, latitude);
        set(19, longitude);
        set(20, swversion);
        set(21, erbtsRemark);
        set(22, extprop1);
        set(23, extprop2);
    }
}
