/*
 * This file is generated by jOOQ.
*/
package id.mit.chrono.server.model.tables.records;


import id.mit.chrono.server.model.tables.Hwbsc;

import javax.annotation.Generated;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HwbscRecord extends UpdatableRecordImpl<HwbscRecord> {

    private static final long serialVersionUID = -837533522;

    /**
     * Setter for <code>chrono.hwbsc.hwbsc_id</code>.
     */
    public void setHwbscId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.hwbsc_id</code>.
     */
    public ULong getHwbscId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>chrono.hwbsc.hwbsc_crcollectortaskfiles</code>.
     */
    public void setHwbscCrcollectortaskfiles(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.hwbsc_crcollectortaskfiles</code>.
     */
    public ULong getHwbscCrcollectortaskfiles() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>chrono.hwbsc.hwbsc_date</code>.
     */
    public void setHwbscDate(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.hwbsc_date</code>.
     */
    public UInteger getHwbscDate() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>chrono.hwbsc.hwbsc_datefrom</code>.
     */
    public void setHwbscDatefrom(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.hwbsc_datefrom</code>.
     */
    public Integer getHwbscDatefrom() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>chrono.hwbsc.hwbsc_node</code>.
     */
    public void setHwbscNode(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.hwbsc_node</code>.
     */
    public Integer getHwbscNode() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>chrono.hwbsc.hwbsc_vendor</code>.
     */
    public void setHwbscVendor(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.hwbsc_vendor</code>.
     */
    public Integer getHwbscVendor() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>chrono.hwbsc.BSCNAME</code>.
     */
    public void setBscname(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.BSCNAME</code>.
     */
    public String getBscname() {
        return (String) get(6);
    }

    /**
     * Setter for <code>chrono.hwbsc.TOTALSUBRACK</code>.
     */
    public void setTotalsubrack(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.TOTALSUBRACK</code>.
     */
    public Integer getTotalsubrack() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>chrono.hwbsc.TOTALBRD</code>.
     */
    public void setTotalbrd(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.TOTALBRD</code>.
     */
    public Integer getTotalbrd() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>chrono.hwbsc.TOTALBTS</code>.
     */
    public void setTotalbts(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.TOTALBTS</code>.
     */
    public Integer getTotalbts() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>chrono.hwbsc.TOTALTRXCAP</code>.
     */
    public void setTotaltrxcap(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.TOTALTRXCAP</code>.
     */
    public Integer getTotaltrxcap() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>chrono.hwbsc.TOTALTRX</code>.
     */
    public void setTotaltrx(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.TOTALTRX</code>.
     */
    public Integer getTotaltrx() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>chrono.hwbsc.TRXOCCUP</code>.
     */
    public void setTrxoccup(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.TRXOCCUP</code>.
     */
    public Double getTrxoccup() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>chrono.hwbsc.TOTALCELL</code>.
     */
    public void setTotalcell(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.TOTALCELL</code>.
     */
    public Integer getTotalcell() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>chrono.hwbsc.FDN</code>.
     */
    public void setFdn(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.FDN</code>.
     */
    public String getFdn() {
        return (String) get(14);
    }

    /**
     * Setter for <code>chrono.hwbsc.IP</code>.
     */
    public void setIp(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.IP</code>.
     */
    public String getIp() {
        return (String) get(15);
    }

    /**
     * Setter for <code>chrono.hwbsc.MOINDEX</code>.
     */
    public void setMoindex(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.MOINDEX</code>.
     */
    public String getMoindex() {
        return (String) get(16);
    }

    /**
     * Setter for <code>chrono.hwbsc.MATCHVERSION</code>.
     */
    public void setMatchversion(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.MATCHVERSION</code>.
     */
    public String getMatchversion() {
        return (String) get(17);
    }

    /**
     * Setter for <code>chrono.hwbsc.MEMO</code>.
     */
    public void setMemo(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.MEMO</code>.
     */
    public String getMemo() {
        return (String) get(18);
    }

    /**
     * Setter for <code>chrono.hwbsc.NEID</code>.
     */
    public void setNeid(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.NEID</code>.
     */
    public String getNeid() {
        return (String) get(19);
    }

    /**
     * Setter for <code>chrono.hwbsc.NETYPE</code>.
     */
    public void setNetype(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.NETYPE</code>.
     */
    public String getNetype() {
        return (String) get(20);
    }

    /**
     * Setter for <code>chrono.hwbsc.NEVERSION</code>.
     */
    public void setNeversion(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.NEVERSION</code>.
     */
    public String getNeversion() {
        return (String) get(21);
    }

    /**
     * Setter for <code>chrono.hwbsc.USERLABEL</code>.
     */
    public void setUserlabel(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.USERLABEL</code>.
     */
    public String getUserlabel() {
        return (String) get(22);
    }

    /**
     * Setter for <code>chrono.hwbsc.VENDORNAME</code>.
     */
    public void setVendorname(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.VENDORNAME</code>.
     */
    public String getVendorname() {
        return (String) get(23);
    }

    /**
     * Setter for <code>chrono.hwbsc.TIMEZONE</code>.
     */
    public void setTimezone(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.TIMEZONE</code>.
     */
    public String getTimezone() {
        return (String) get(24);
    }

    /**
     * Setter for <code>chrono.hwbsc.hwbsc_remark</code>.
     */
    public void setHwbscRemark(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.hwbsc_remark</code>.
     */
    public String getHwbscRemark() {
        return (String) get(25);
    }

    /**
     * Setter for <code>chrono.hwbsc.EXTPROP1</code>.
     */
    public void setExtprop1(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.EXTPROP1</code>.
     */
    public String getExtprop1() {
        return (String) get(26);
    }

    /**
     * Setter for <code>chrono.hwbsc.EXTPROP2</code>.
     */
    public void setExtprop2(Integer value) {
        set(27, value);
    }

    /**
     * Getter for <code>chrono.hwbsc.EXTPROP2</code>.
     */
    public Integer getExtprop2() {
        return (Integer) get(27);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<ULong, ULong> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HwbscRecord
     */
    public HwbscRecord() {
        super(Hwbsc.HWBSC);
    }

    /**
     * Create a detached, initialised HwbscRecord
     */
    public HwbscRecord(ULong hwbscId, ULong hwbscCrcollectortaskfiles, UInteger hwbscDate, Integer hwbscDatefrom, Integer hwbscNode, Integer hwbscVendor, String bscname, Integer totalsubrack, Integer totalbrd, Integer totalbts, Integer totaltrxcap, Integer totaltrx, Double trxoccup, Integer totalcell, String fdn, String ip, String moindex, String matchversion, String memo, String neid, String netype, String neversion, String userlabel, String vendorname, String timezone, String hwbscRemark, String extprop1, Integer extprop2) {
        super(Hwbsc.HWBSC);

        set(0, hwbscId);
        set(1, hwbscCrcollectortaskfiles);
        set(2, hwbscDate);
        set(3, hwbscDatefrom);
        set(4, hwbscNode);
        set(5, hwbscVendor);
        set(6, bscname);
        set(7, totalsubrack);
        set(8, totalbrd);
        set(9, totalbts);
        set(10, totaltrxcap);
        set(11, totaltrx);
        set(12, trxoccup);
        set(13, totalcell);
        set(14, fdn);
        set(15, ip);
        set(16, moindex);
        set(17, matchversion);
        set(18, memo);
        set(19, neid);
        set(20, netype);
        set(21, neversion);
        set(22, userlabel);
        set(23, vendorname);
        set(24, timezone);
        set(25, hwbscRemark);
        set(26, extprop1);
        set(27, extprop2);
    }
}
