/*
 * This file is generated by jOOQ.
*/
package id.mit.chrono.server.model.tables.records;


import id.mit.chrono.server.model.tables.Hwbts;

import javax.annotation.Generated;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HwbtsRecord extends UpdatableRecordImpl<HwbtsRecord> {

    private static final long serialVersionUID = -370823035;

    /**
     * Setter for <code>chrono.hwbts.hwbts_id</code>.
     */
    public void setHwbtsId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>chrono.hwbts.hwbts_id</code>.
     */
    public ULong getHwbtsId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>chrono.hwbts.hwbts_crcollectortaskfiles</code>.
     */
    public void setHwbtsCrcollectortaskfiles(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>chrono.hwbts.hwbts_crcollectortaskfiles</code>.
     */
    public ULong getHwbtsCrcollectortaskfiles() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>chrono.hwbts.hwbts_date</code>.
     */
    public void setHwbtsDate(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>chrono.hwbts.hwbts_date</code>.
     */
    public UInteger getHwbtsDate() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>chrono.hwbts.hwbts_datefrom</code>.
     */
    public void setHwbtsDatefrom(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>chrono.hwbts.hwbts_datefrom</code>.
     */
    public Integer getHwbtsDatefrom() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>chrono.hwbts.hwbts_hwbsc</code>.
     */
    public void setHwbtsHwbsc(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>chrono.hwbts.hwbts_hwbsc</code>.
     */
    public ULong getHwbtsHwbsc() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>chrono.hwbts.hwbts_node</code>.
     */
    public void setHwbtsNode(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>chrono.hwbts.hwbts_node</code>.
     */
    public Integer getHwbtsNode() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>chrono.hwbts.hwbts_nodephysical</code>.
     */
    public void setHwbtsNodephysical(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>chrono.hwbts.hwbts_nodephysical</code>.
     */
    public Integer getHwbtsNodephysical() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>chrono.hwbts.hwbts_nodestatus</code>.
     */
    public void setHwbtsNodestatus(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>chrono.hwbts.hwbts_nodestatus</code>.
     */
    public Integer getHwbtsNodestatus() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>chrono.hwbts.hwbts_revenueclass</code>.
     */
    public void setHwbtsRevenueclass(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>chrono.hwbts.hwbts_revenueclass</code>.
     */
    public Integer getHwbtsRevenueclass() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>chrono.hwbts.hwbts_vendor</code>.
     */
    public void setHwbtsVendor(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>chrono.hwbts.hwbts_vendor</code>.
     */
    public Integer getHwbtsVendor() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>chrono.hwbts.hwbts_namingvalid</code>.
     */
    public void setHwbtsNamingvalid(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>chrono.hwbts.hwbts_namingvalid</code>.
     */
    public Byte getHwbtsNamingvalid() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>chrono.hwbts.TOTALCELL</code>.
     */
    public void setTotalcell(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>chrono.hwbts.TOTALCELL</code>.
     */
    public Integer getTotalcell() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>chrono.hwbts.TOTALTRX</code>.
     */
    public void setTotaltrx(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>chrono.hwbts.TOTALTRX</code>.
     */
    public Integer getTotaltrx() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>chrono.hwbts.BTSNAME</code>.
     */
    public void setBtsname(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>chrono.hwbts.BTSNAME</code>.
     */
    public String getBtsname() {
        return (String) get(13);
    }

    /**
     * Setter for <code>chrono.hwbts.BTSID</code>.
     */
    public void setBtsid(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>chrono.hwbts.BTSID</code>.
     */
    public String getBtsid() {
        return (String) get(14);
    }

    /**
     * Setter for <code>chrono.hwbts.FDN</code>.
     */
    public void setFdn(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>chrono.hwbts.FDN</code>.
     */
    public String getFdn() {
        return (String) get(15);
    }

    /**
     * Setter for <code>chrono.hwbts.ACTSTATUS</code>.
     */
    public void setActstatus(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>chrono.hwbts.ACTSTATUS</code>.
     */
    public String getActstatus() {
        return (String) get(16);
    }

    /**
     * Setter for <code>chrono.hwbts.BTSDESC</code>.
     */
    public void setBtsdesc(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>chrono.hwbts.BTSDESC</code>.
     */
    public String getBtsdesc() {
        return (String) get(17);
    }

    /**
     * Setter for <code>chrono.hwbts.BTSTYPE</code>.
     */
    public void setBtstype(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>chrono.hwbts.BTSTYPE</code>.
     */
    public String getBtstype() {
        return (String) get(18);
    }

    /**
     * Setter for <code>chrono.hwbts.MOINDEX</code>.
     */
    public void setMoindex(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>chrono.hwbts.MOINDEX</code>.
     */
    public String getMoindex() {
        return (String) get(19);
    }

    /**
     * Setter for <code>chrono.hwbts.SERVICEMODE</code>.
     */
    public void setServicemode(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>chrono.hwbts.SERVICEMODE</code>.
     */
    public String getServicemode() {
        return (String) get(20);
    }

    /**
     * Setter for <code>chrono.hwbts.MPMODE</code>.
     */
    public void setMpmode(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>chrono.hwbts.MPMODE</code>.
     */
    public String getMpmode() {
        return (String) get(21);
    }

    /**
     * Setter for <code>chrono.hwbts.SRANMODE</code>.
     */
    public void setSranmode(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>chrono.hwbts.SRANMODE</code>.
     */
    public String getSranmode() {
        return (String) get(22);
    }

    /**
     * Setter for <code>chrono.hwbts.NEID</code>.
     */
    public void setNeid(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>chrono.hwbts.NEID</code>.
     */
    public String getNeid() {
        return (String) get(23);
    }

    /**
     * Setter for <code>chrono.hwbts.FLEXABISMODE</code>.
     */
    public void setFlexabismode(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>chrono.hwbts.FLEXABISMODE</code>.
     */
    public String getFlexabismode() {
        return (String) get(24);
    }

    /**
     * Setter for <code>chrono.hwbts.IPPHYTRANSTYPE</code>.
     */
    public void setIpphytranstype(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>chrono.hwbts.IPPHYTRANSTYPE</code>.
     */
    public String getIpphytranstype() {
        return (String) get(25);
    }

    /**
     * Setter for <code>chrono.hwbts.LATITUDEDEGFORMAT</code>.
     */
    public void setLatitudedegformat(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>chrono.hwbts.LATITUDEDEGFORMAT</code>.
     */
    public String getLatitudedegformat() {
        return (String) get(26);
    }

    /**
     * Setter for <code>chrono.hwbts.LONGITUDEDEGFORMAT</code>.
     */
    public void setLongitudedegformat(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>chrono.hwbts.LONGITUDEDEGFORMAT</code>.
     */
    public String getLongitudedegformat() {
        return (String) get(27);
    }

    /**
     * Setter for <code>chrono.hwbts.hwbts_remark</code>.
     */
    public void setHwbtsRemark(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>chrono.hwbts.hwbts_remark</code>.
     */
    public String getHwbtsRemark() {
        return (String) get(28);
    }

    /**
     * Setter for <code>chrono.hwbts.ANI</code>.
     */
    public void setAni(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>chrono.hwbts.ANI</code>.
     */
    public String getAni() {
        return (String) get(29);
    }

    /**
     * Setter for <code>chrono.hwbts.EXTPROP1</code>.
     */
    public void setExtprop1(Integer value) {
        set(30, value);
    }

    /**
     * Getter for <code>chrono.hwbts.EXTPROP1</code>.
     */
    public Integer getExtprop1() {
        return (Integer) get(30);
    }

    /**
     * Setter for <code>chrono.hwbts.EXTPROP2</code>.
     */
    public void setExtprop2(Integer value) {
        set(31, value);
    }

    /**
     * Getter for <code>chrono.hwbts.EXTPROP2</code>.
     */
    public Integer getExtprop2() {
        return (Integer) get(31);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<ULong, ULong> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HwbtsRecord
     */
    public HwbtsRecord() {
        super(Hwbts.HWBTS);
    }

    /**
     * Create a detached, initialised HwbtsRecord
     */
    public HwbtsRecord(ULong hwbtsId, ULong hwbtsCrcollectortaskfiles, UInteger hwbtsDate, Integer hwbtsDatefrom, ULong hwbtsHwbsc, Integer hwbtsNode, Integer hwbtsNodephysical, Integer hwbtsNodestatus, Integer hwbtsRevenueclass, Integer hwbtsVendor, Byte hwbtsNamingvalid, Integer totalcell, Integer totaltrx, String btsname, String btsid, String fdn, String actstatus, String btsdesc, String btstype, String moindex, String servicemode, String mpmode, String sranmode, String neid, String flexabismode, String ipphytranstype, String latitudedegformat, String longitudedegformat, String hwbtsRemark, String ani, Integer extprop1, Integer extprop2) {
        super(Hwbts.HWBTS);

        set(0, hwbtsId);
        set(1, hwbtsCrcollectortaskfiles);
        set(2, hwbtsDate);
        set(3, hwbtsDatefrom);
        set(4, hwbtsHwbsc);
        set(5, hwbtsNode);
        set(6, hwbtsNodephysical);
        set(7, hwbtsNodestatus);
        set(8, hwbtsRevenueclass);
        set(9, hwbtsVendor);
        set(10, hwbtsNamingvalid);
        set(11, totalcell);
        set(12, totaltrx);
        set(13, btsname);
        set(14, btsid);
        set(15, fdn);
        set(16, actstatus);
        set(17, btsdesc);
        set(18, btstype);
        set(19, moindex);
        set(20, servicemode);
        set(21, mpmode);
        set(22, sranmode);
        set(23, neid);
        set(24, flexabismode);
        set(25, ipphytranstype);
        set(26, latitudedegformat);
        set(27, longitudedegformat);
        set(28, hwbtsRemark);
        set(29, ani);
        set(30, extprop1);
        set(31, extprop2);
    }
}
