/*
 * This file is generated by jOOQ.
*/
package id.mit.chrono.server.model.tables.records;


import id.mit.chrono.server.model.tables.Hwnodeb;

import javax.annotation.Generated;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HwnodebRecord extends UpdatableRecordImpl<HwnodebRecord> {

    private static final long serialVersionUID = -83016245;

    /**
     * Setter for <code>chrono.hwnodeb.hwnodeb_id</code>.
     */
    public void setHwnodebId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.hwnodeb_id</code>.
     */
    public ULong getHwnodebId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>chrono.hwnodeb.hwnodeb_crcollectortaskfiles</code>.
     */
    public void setHwnodebCrcollectortaskfiles(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.hwnodeb_crcollectortaskfiles</code>.
     */
    public ULong getHwnodebCrcollectortaskfiles() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>chrono.hwnodeb.hwnodeb_date</code>.
     */
    public void setHwnodebDate(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.hwnodeb_date</code>.
     */
    public UInteger getHwnodebDate() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>chrono.hwnodeb.hwnodeb_datefrom</code>.
     */
    public void setHwnodebDatefrom(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.hwnodeb_datefrom</code>.
     */
    public Integer getHwnodebDatefrom() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>chrono.hwnodeb.hwnodeb_hwrnc</code>.
     */
    public void setHwnodebHwrnc(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.hwnodeb_hwrnc</code>.
     */
    public ULong getHwnodebHwrnc() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>chrono.hwnodeb.hwnodeb_node</code>.
     */
    public void setHwnodebNode(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.hwnodeb_node</code>.
     */
    public Integer getHwnodebNode() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>chrono.hwnodeb.hwnodeb_nodephysical</code>.
     */
    public void setHwnodebNodephysical(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.hwnodeb_nodephysical</code>.
     */
    public Integer getHwnodebNodephysical() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>chrono.hwnodeb.hwnodeb_nodestatus</code>.
     */
    public void setHwnodebNodestatus(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.hwnodeb_nodestatus</code>.
     */
    public Integer getHwnodebNodestatus() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>chrono.hwnodeb.hwnodeb_revenueclass</code>.
     */
    public void setHwnodebRevenueclass(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.hwnodeb_revenueclass</code>.
     */
    public Integer getHwnodebRevenueclass() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>chrono.hwnodeb.hwnodeb_vendor</code>.
     */
    public void setHwnodebVendor(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.hwnodeb_vendor</code>.
     */
    public Integer getHwnodebVendor() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>chrono.hwnodeb.hwnodeb_namingvalid</code>.
     */
    public void setHwnodebNamingvalid(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.hwnodeb_namingvalid</code>.
     */
    public Byte getHwnodebNamingvalid() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>chrono.hwnodeb.NODEBID</code>.
     */
    public void setNodebid(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.NODEBID</code>.
     */
    public String getNodebid() {
        return (String) get(11);
    }

    /**
     * Setter for <code>chrono.hwnodeb.LOGICRNCID</code>.
     */
    public void setLogicrncid(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.LOGICRNCID</code>.
     */
    public String getLogicrncid() {
        return (String) get(12);
    }

    /**
     * Setter for <code>chrono.hwnodeb.NODEBNAME</code>.
     */
    public void setNodebname(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.NODEBNAME</code>.
     */
    public String getNodebname() {
        return (String) get(13);
    }

    /**
     * Setter for <code>chrono.hwnodeb.TOTALCELL</code>.
     */
    public void setTotalcell(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.TOTALCELL</code>.
     */
    public Integer getTotalcell() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>chrono.hwnodeb.FDN</code>.
     */
    public void setFdn(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.FDN</code>.
     */
    public String getFdn() {
        return (String) get(15);
    }

    /**
     * Setter for <code>chrono.hwnodeb.HOSTTYPE</code>.
     */
    public void setHosttype(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.HOSTTYPE</code>.
     */
    public String getHosttype() {
        return (String) get(16);
    }

    /**
     * Setter for <code>chrono.hwnodeb.BTSTYPE</code>.
     */
    public void setBtstype(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.BTSTYPE</code>.
     */
    public String getBtstype() {
        return (String) get(17);
    }

    /**
     * Setter for <code>chrono.hwnodeb.NBOAMIP</code>.
     */
    public void setNboamip(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.NBOAMIP</code>.
     */
    public String getNboamip() {
        return (String) get(18);
    }

    /**
     * Setter for <code>chrono.hwnodeb.NBOAMMASK</code>.
     */
    public void setNboammask(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.NBOAMMASK</code>.
     */
    public String getNboammask() {
        return (String) get(19);
    }

    /**
     * Setter for <code>chrono.hwnodeb.TNLBEARERTYPE</code>.
     */
    public void setTnlbearertype(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.TNLBEARERTYPE</code>.
     */
    public String getTnlbearertype() {
        return (String) get(20);
    }

    /**
     * Setter for <code>chrono.hwnodeb.RSCMNGMODE</code>.
     */
    public void setRscmngmode(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.RSCMNGMODE</code>.
     */
    public String getRscmngmode() {
        return (String) get(21);
    }

    /**
     * Setter for <code>chrono.hwnodeb.SATELLITEIND</code>.
     */
    public void setSatelliteind(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.SATELLITEIND</code>.
     */
    public String getSatelliteind() {
        return (String) get(22);
    }

    /**
     * Setter for <code>chrono.hwnodeb.SHARINGTYPE</code>.
     */
    public void setSharingtype(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.SHARINGTYPE</code>.
     */
    public String getSharingtype() {
        return (String) get(23);
    }

    /**
     * Setter for <code>chrono.hwnodeb.TRANSDELAY</code>.
     */
    public void setTransdelay(Integer value) {
        set(24, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.TRANSDELAY</code>.
     */
    public Integer getTransdelay() {
        return (Integer) get(24);
    }

    /**
     * Setter for <code>chrono.hwnodeb.NAME</code>.
     */
    public void setName(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.NAME</code>.
     */
    public String getName() {
        return (String) get(25);
    }

    /**
     * Setter for <code>chrono.hwnodeb.NEID</code>.
     */
    public void setNeid(Integer value) {
        set(26, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.NEID</code>.
     */
    public Integer getNeid() {
        return (Integer) get(26);
    }

    /**
     * Setter for <code>chrono.hwnodeb.BLKSTATUS</code>.
     */
    public void setBlkstatus(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.BLKSTATUS</code>.
     */
    public String getBlkstatus() {
        return (String) get(27);
    }

    /**
     * Setter for <code>chrono.hwnodeb.NODEBPROTCLVER</code>.
     */
    public void setNodebprotclver(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.NODEBPROTCLVER</code>.
     */
    public String getNodebprotclver() {
        return (String) get(28);
    }

    /**
     * Setter for <code>chrono.hwnodeb.ANI</code>.
     */
    public void setAni(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.ANI</code>.
     */
    public String getAni() {
        return (String) get(29);
    }

    /**
     * Setter for <code>chrono.hwnodeb.hwnodeb_remark</code>.
     */
    public void setHwnodebRemark(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.hwnodeb_remark</code>.
     */
    public String getHwnodebRemark() {
        return (String) get(30);
    }

    /**
     * Setter for <code>chrono.hwnodeb.TXBW</code>.
     */
    public void setTxbw(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.TXBW</code>.
     */
    public String getTxbw() {
        return (String) get(31);
    }

    /**
     * Setter for <code>chrono.hwnodeb.RXBW</code>.
     */
    public void setRxbw(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.RXBW</code>.
     */
    public String getRxbw() {
        return (String) get(32);
    }

    /**
     * Setter for <code>chrono.hwnodeb.EXTPROP1</code>.
     */
    public void setExtprop1(Integer value) {
        set(33, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.EXTPROP1</code>.
     */
    public Integer getExtprop1() {
        return (Integer) get(33);
    }

    /**
     * Setter for <code>chrono.hwnodeb.EXTPROP2</code>.
     */
    public void setExtprop2(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>chrono.hwnodeb.EXTPROP2</code>.
     */
    public String getExtprop2() {
        return (String) get(34);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<ULong, ULong> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HwnodebRecord
     */
    public HwnodebRecord() {
        super(Hwnodeb.HWNODEB);
    }

    /**
     * Create a detached, initialised HwnodebRecord
     */
    public HwnodebRecord(ULong hwnodebId, ULong hwnodebCrcollectortaskfiles, UInteger hwnodebDate, Integer hwnodebDatefrom, ULong hwnodebHwrnc, Integer hwnodebNode, Integer hwnodebNodephysical, Integer hwnodebNodestatus, Integer hwnodebRevenueclass, Integer hwnodebVendor, Byte hwnodebNamingvalid, String nodebid, String logicrncid, String nodebname, Integer totalcell, String fdn, String hosttype, String btstype, String nboamip, String nboammask, String tnlbearertype, String rscmngmode, String satelliteind, String sharingtype, Integer transdelay, String name, Integer neid, String blkstatus, String nodebprotclver, String ani, String hwnodebRemark, String txbw, String rxbw, Integer extprop1, String extprop2) {
        super(Hwnodeb.HWNODEB);

        set(0, hwnodebId);
        set(1, hwnodebCrcollectortaskfiles);
        set(2, hwnodebDate);
        set(3, hwnodebDatefrom);
        set(4, hwnodebHwrnc);
        set(5, hwnodebNode);
        set(6, hwnodebNodephysical);
        set(7, hwnodebNodestatus);
        set(8, hwnodebRevenueclass);
        set(9, hwnodebVendor);
        set(10, hwnodebNamingvalid);
        set(11, nodebid);
        set(12, logicrncid);
        set(13, nodebname);
        set(14, totalcell);
        set(15, fdn);
        set(16, hosttype);
        set(17, btstype);
        set(18, nboamip);
        set(19, nboammask);
        set(20, tnlbearertype);
        set(21, rscmngmode);
        set(22, satelliteind);
        set(23, sharingtype);
        set(24, transdelay);
        set(25, name);
        set(26, neid);
        set(27, blkstatus);
        set(28, nodebprotclver);
        set(29, ani);
        set(30, hwnodebRemark);
        set(31, txbw);
        set(32, rxbw);
        set(33, extprop1);
        set(34, extprop2);
    }
}
