/*
 * This file is generated by jOOQ.
*/
package id.mit.chrono.server.model.tables.records;


import id.mit.chrono.server.model.tables.Inventoryfieldvalidation;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoryfieldvalidationRecord extends UpdatableRecordImpl<InventoryfieldvalidationRecord> implements Record7<UInteger, String, String, String, String, String, Integer> {

    private static final long serialVersionUID = 640298398;

    /**
     * Setter for <code>chrono.inventoryfieldvalidation.inventorypartvalidation_id</code>.
     */
    public void setInventorypartvalidationId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>chrono.inventoryfieldvalidation.inventorypartvalidation_id</code>.
     */
    public UInteger getInventorypartvalidationId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>chrono.inventoryfieldvalidation.inventorypartvalidation_code</code>.
     */
    public void setInventorypartvalidationCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>chrono.inventoryfieldvalidation.inventorypartvalidation_code</code>.
     */
    public String getInventorypartvalidationCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>chrono.inventoryfieldvalidation.inventorypartvalidation_table</code>.
     */
    public void setInventorypartvalidationTable(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>chrono.inventoryfieldvalidation.inventorypartvalidation_table</code>.
     */
    public String getInventorypartvalidationTable() {
        return (String) get(2);
    }

    /**
     * Setter for <code>chrono.inventoryfieldvalidation.inventorypartvalidation_field</code>.
     */
    public void setInventorypartvalidationField(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>chrono.inventoryfieldvalidation.inventorypartvalidation_field</code>.
     */
    public String getInventorypartvalidationField() {
        return (String) get(3);
    }

    /**
     * Setter for <code>chrono.inventoryfieldvalidation.inventorypartvalidation_pattern</code>.
     */
    public void setInventorypartvalidationPattern(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>chrono.inventoryfieldvalidation.inventorypartvalidation_pattern</code>.
     */
    public String getInventorypartvalidationPattern() {
        return (String) get(4);
    }

    /**
     * Setter for <code>chrono.inventoryfieldvalidation.inventorypartvalidation_action</code>.
     */
    public void setInventorypartvalidationAction(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>chrono.inventoryfieldvalidation.inventorypartvalidation_action</code>.
     */
    public String getInventorypartvalidationAction() {
        return (String) get(5);
    }

    /**
     * Setter for <code>chrono.inventoryfieldvalidation.inventorypartvalidation_enable</code>.
     */
    public void setInventorypartvalidationEnable(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>chrono.inventoryfieldvalidation.inventorypartvalidation_enable</code>.
     */
    public Integer getInventorypartvalidationEnable() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, String, String, String, String, String, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, String, String, String, String, String, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Inventoryfieldvalidation.INVENTORYFIELDVALIDATION.INVENTORYPARTVALIDATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Inventoryfieldvalidation.INVENTORYFIELDVALIDATION.INVENTORYPARTVALIDATION_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Inventoryfieldvalidation.INVENTORYFIELDVALIDATION.INVENTORYPARTVALIDATION_TABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Inventoryfieldvalidation.INVENTORYFIELDVALIDATION.INVENTORYPARTVALIDATION_FIELD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Inventoryfieldvalidation.INVENTORYFIELDVALIDATION.INVENTORYPARTVALIDATION_PATTERN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Inventoryfieldvalidation.INVENTORYFIELDVALIDATION.INVENTORYPARTVALIDATION_ACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Inventoryfieldvalidation.INVENTORYFIELDVALIDATION.INVENTORYPARTVALIDATION_ENABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getInventorypartvalidationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getInventorypartvalidationCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getInventorypartvalidationTable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getInventorypartvalidationField();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getInventorypartvalidationPattern();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getInventorypartvalidationAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getInventorypartvalidationEnable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getInventorypartvalidationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getInventorypartvalidationCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getInventorypartvalidationTable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getInventorypartvalidationField();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getInventorypartvalidationPattern();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getInventorypartvalidationAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getInventorypartvalidationEnable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryfieldvalidationRecord value1(UInteger value) {
        setInventorypartvalidationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryfieldvalidationRecord value2(String value) {
        setInventorypartvalidationCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryfieldvalidationRecord value3(String value) {
        setInventorypartvalidationTable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryfieldvalidationRecord value4(String value) {
        setInventorypartvalidationField(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryfieldvalidationRecord value5(String value) {
        setInventorypartvalidationPattern(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryfieldvalidationRecord value6(String value) {
        setInventorypartvalidationAction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryfieldvalidationRecord value7(Integer value) {
        setInventorypartvalidationEnable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryfieldvalidationRecord values(UInteger value1, String value2, String value3, String value4, String value5, String value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryfieldvalidationRecord
     */
    public InventoryfieldvalidationRecord() {
        super(Inventoryfieldvalidation.INVENTORYFIELDVALIDATION);
    }

    /**
     * Create a detached, initialised InventoryfieldvalidationRecord
     */
    public InventoryfieldvalidationRecord(UInteger inventorypartvalidationId, String inventorypartvalidationCode, String inventorypartvalidationTable, String inventorypartvalidationField, String inventorypartvalidationPattern, String inventorypartvalidationAction, Integer inventorypartvalidationEnable) {
        super(Inventoryfieldvalidation.INVENTORYFIELDVALIDATION);

        set(0, inventorypartvalidationId);
        set(1, inventorypartvalidationCode);
        set(2, inventorypartvalidationTable);
        set(3, inventorypartvalidationField);
        set(4, inventorypartvalidationPattern);
        set(5, inventorypartvalidationAction);
        set(6, inventorypartvalidationEnable);
    }
}
