/*
 * This file is generated by jOOQ.
*/
package id.mit.chrono.server.model.tables.records;


import id.mit.chrono.server.model.tables.TempCrstatic;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TempCrstaticRecord extends UpdatableRecordImpl<TempCrstaticRecord> {

    private static final long serialVersionUID = -1920127891;

    /**
     * Setter for <code>chrono.temp_crstatic.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.STATUS</code>.
     */
    public void setStatus(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(1);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.CELL</code>.
     */
    public void setCell(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.CELL</code>.
     */
    public String getCell() {
        return (String) get(2);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.SITE</code>.
     */
    public void setSite(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.SITE</code>.
     */
    public String getSite() {
        return (String) get(3);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.NE</code>.
     */
    public void setNe(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.NE</code>.
     */
    public String getNe() {
        return (String) get(4);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.NE2G</code>.
     */
    public void setNe2g(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.NE2G</code>.
     */
    public String getNe2g() {
        return (String) get(5);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.NE4G</code>.
     */
    public void setNe4g(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.NE4G</code>.
     */
    public String getNe4g() {
        return (String) get(6);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.SITEID</code>.
     */
    public void setSiteid(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.SITEID</code>.
     */
    public String getSiteid() {
        return (String) get(7);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.NEID</code>.
     */
    public void setNeid(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.NEID</code>.
     */
    public String getNeid() {
        return (String) get(8);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.SITENAME</code>.
     */
    public void setSitename(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.SITENAME</code>.
     */
    public String getSitename() {
        return (String) get(9);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.CELLNAME</code>.
     */
    public void setCellname(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.CELLNAME</code>.
     */
    public String getCellname() {
        return (String) get(10);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.DESA</code>.
     */
    public void setDesa(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.DESA</code>.
     */
    public String getDesa() {
        return (String) get(11);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.KECAMATAN</code>.
     */
    public void setKecamatan(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.KECAMATAN</code>.
     */
    public String getKecamatan() {
        return (String) get(12);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.KABUPATEN</code>.
     */
    public void setKabupaten(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.KABUPATEN</code>.
     */
    public String getKabupaten() {
        return (String) get(13);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.PROVINSI</code>.
     */
    public void setProvinsi(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.PROVINSI</code>.
     */
    public String getProvinsi() {
        return (String) get(14);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.LATDRM</code>.
     */
    public void setLatdrm(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.LATDRM</code>.
     */
    public String getLatdrm() {
        return (String) get(15);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.LONGDRM</code>.
     */
    public void setLongdrm(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.LONGDRM</code>.
     */
    public String getLongdrm() {
        return (String) get(16);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.LATDT</code>.
     */
    public void setLatdt(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.LATDT</code>.
     */
    public String getLatdt() {
        return (String) get(17);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.LONGDT</code>.
     */
    public void setLongdt(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.LONGDT</code>.
     */
    public String getLongdt() {
        return (String) get(18);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.LAT</code>.
     */
    public void setLat(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.LAT</code>.
     */
    public String getLat() {
        return (String) get(19);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.LONG</code>.
     */
    public void setLong(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.LONG</code>.
     */
    public String getLong() {
        return (String) get(20);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.REGIONAL</code>.
     */
    public void setRegional(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.REGIONAL</code>.
     */
    public String getRegional() {
        return (String) get(21);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.AREA</code>.
     */
    public void setArea(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.AREA</code>.
     */
    public String getArea() {
        return (String) get(22);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.NEIGBOURCOUNTRY</code>.
     */
    public void setNeigbourcountry(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.NEIGBOURCOUNTRY</code>.
     */
    public String getNeigbourcountry() {
        return (String) get(23);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.SITETYPE</code>.
     */
    public void setSitetype(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.SITETYPE</code>.
     */
    public String getSitetype() {
        return (String) get(24);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.PROJECT</code>.
     */
    public void setProject(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.PROJECT</code>.
     */
    public String getProject() {
        return (String) get(25);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.KLASIFIKASIPROJECT</code>.
     */
    public void setKlasifikasiproject(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.KLASIFIKASIPROJECT</code>.
     */
    public String getKlasifikasiproject() {
        return (String) get(26);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.PROJECTTRACKING</code>.
     */
    public void setProjecttracking(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.PROJECTTRACKING</code>.
     */
    public String getProjecttracking() {
        return (String) get(27);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.TGLCONNECTED</code>.
     */
    public void setTglconnected(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.TGLCONNECTED</code>.
     */
    public String getTglconnected() {
        return (String) get(28);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.TGLOA</code>.
     */
    public void setTgloa(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.TGLOA</code>.
     */
    public String getTgloa() {
        return (String) get(29);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.TECHNOLOGYCOLO</code>.
     */
    public void setTechnologycolo(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.TECHNOLOGYCOLO</code>.
     */
    public String getTechnologycolo() {
        return (String) get(30);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.NETWORK</code>.
     */
    public void setNetwork(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.NETWORK</code>.
     */
    public String getNetwork() {
        return (String) get(31);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.BAND</code>.
     */
    public void setBand(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.BAND</code>.
     */
    public String getBand() {
        return (String) get(32);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.BTSSECTOR</code>.
     */
    public void setBtssector(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.BTSSECTOR</code>.
     */
    public String getBtssector() {
        return (String) get(33);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.TRXCELL</code>.
     */
    public void setTrxcell(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.TRXCELL</code>.
     */
    public String getTrxcell() {
        return (String) get(34);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.LAC</code>.
     */
    public void setLac(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.LAC</code>.
     */
    public String getLac() {
        return (String) get(35);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.CELLID</code>.
     */
    public void setCellid(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.CELLID</code>.
     */
    public String getCellid() {
        return (String) get(36);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.LACCI</code>.
     */
    public void setLacci(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.LACCI</code>.
     */
    public String getLacci() {
        return (String) get(37);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.BSCNAME</code>.
     */
    public void setBscname(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.BSCNAME</code>.
     */
    public String getBscname() {
        return (String) get(38);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.BSCSPC</code>.
     */
    public void setBscspc(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.BSCSPC</code>.
     */
    public String getBscspc() {
        return (String) get(39);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.RAC</code>.
     */
    public void setRac(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.RAC</code>.
     */
    public String getRac() {
        return (String) get(40);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.MSSSPC</code>.
     */
    public void setMssspc(String value) {
        set(41, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.MSSSPC</code>.
     */
    public String getMssspc() {
        return (String) get(41);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.MGWNAME</code>.
     */
    public void setMgwname(String value) {
        set(42, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.MGWNAME</code>.
     */
    public String getMgwname() {
        return (String) get(42);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.MSSNAME</code>.
     */
    public void setMssname(String value) {
        set(43, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.MSSNAME</code>.
     */
    public String getMssname() {
        return (String) get(43);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.SGSN</code>.
     */
    public void setSgsn(String value) {
        set(44, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.SGSN</code>.
     */
    public String getSgsn() {
        return (String) get(44);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.TAL</code>.
     */
    public void setTal(String value) {
        set(45, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.TAL</code>.
     */
    public String getTal() {
        return (String) get(45);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.TAC</code>.
     */
    public void setTac(String value) {
        set(46, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.TAC</code>.
     */
    public String getTac() {
        return (String) get(46);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.PCI</code>.
     */
    public void setPci(String value) {
        set(47, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.PCI</code>.
     */
    public String getPci() {
        return (String) get(47);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.ULFREQ</code>.
     */
    public void setUlfreq(String value) {
        set(48, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.ULFREQ</code>.
     */
    public String getUlfreq() {
        return (String) get(48);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.DLFREQ</code>.
     */
    public void setDlfreq(String value) {
        set(49, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.DLFREQ</code>.
     */
    public String getDlfreq() {
        return (String) get(49);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.MME</code>.
     */
    public void setMme(String value) {
        set(50, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.MME</code>.
     */
    public String getMme() {
        return (String) get(50);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.SGW</code>.
     */
    public void setSgw(String value) {
        set(51, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.SGW</code>.
     */
    public String getSgw() {
        return (String) get(51);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.TARIFFZONE</code>.
     */
    public void setTariffzone(String value) {
        set(52, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.TARIFFZONE</code>.
     */
    public String getTariffzone() {
        return (String) get(52);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.TYPENAME</code>.
     */
    public void setTypename(String value) {
        set(53, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.TYPENAME</code>.
     */
    public String getTypename() {
        return (String) get(53);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.BTSSDR</code>.
     */
    public void setBtssdr(String value) {
        set(54, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.BTSSDR</code>.
     */
    public String getBtssdr() {
        return (String) get(54);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.BTSTYPE</code>.
     */
    public void setBtstype(String value) {
        set(55, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.BTSTYPE</code>.
     */
    public String getBtstype() {
        return (String) get(55);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.BTSCAT</code>.
     */
    public void setBtscat(String value) {
        set(56, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.BTSCAT</code>.
     */
    public String getBtscat() {
        return (String) get(56);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.BTSVENDOR</code>.
     */
    public void setBtsvendor(String value) {
        set(57, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.BTSVENDOR</code>.
     */
    public String getBtsvendor() {
        return (String) get(57);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.ANTENNATYPE</code>.
     */
    public void setAntennatype(String value) {
        set(58, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.ANTENNATYPE</code>.
     */
    public String getAntennatype() {
        return (String) get(58);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.ANTENNACAT</code>.
     */
    public void setAntennacat(String value) {
        set(59, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.ANTENNACAT</code>.
     */
    public String getAntennacat() {
        return (String) get(59);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.SEWAANTENNA</code>.
     */
    public void setSewaantenna(String value) {
        set(60, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.SEWAANTENNA</code>.
     */
    public String getSewaantenna() {
        return (String) get(60);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.ANTENNAVENDOR</code>.
     */
    public void setAntennavendor(String value) {
        set(61, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.ANTENNAVENDOR</code>.
     */
    public String getAntennavendor() {
        return (String) get(61);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.TOWERTYPE</code>.
     */
    public void setTowertype(String value) {
        set(62, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.TOWERTYPE</code>.
     */
    public String getTowertype() {
        return (String) get(62);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.TOWERCATEGORY</code>.
     */
    public void setTowercategory(String value) {
        set(63, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.TOWERCATEGORY</code>.
     */
    public String getTowercategory() {
        return (String) get(63);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.SEWATOWER</code>.
     */
    public void setSewatower(String value) {
        set(64, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.SEWATOWER</code>.
     */
    public String getSewatower() {
        return (String) get(64);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.TOWERVENDOR</code>.
     */
    public void setTowervendor(String value) {
        set(65, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.TOWERVENDOR</code>.
     */
    public String getTowervendor() {
        return (String) get(65);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.POWERTYPE</code>.
     */
    public void setPowertype(String value) {
        set(66, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.POWERTYPE</code>.
     */
    public String getPowertype() {
        return (String) get(66);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.POWERSUMMARY</code>.
     */
    public void setPowersummary(String value) {
        set(67, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.POWERSUMMARY</code>.
     */
    public String getPowersummary() {
        return (String) get(67);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.POWERCATEGORY</code>.
     */
    public void setPowercategory(String value) {
        set(68, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.POWERCATEGORY</code>.
     */
    public String getPowercategory() {
        return (String) get(68);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.SEWAPOWER</code>.
     */
    public void setSewapower(String value) {
        set(69, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.SEWAPOWER</code>.
     */
    public String getSewapower() {
        return (String) get(69);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.POWERVENDOR</code>.
     */
    public void setPowervendor(String value) {
        set(70, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.POWERVENDOR</code>.
     */
    public String getPowervendor() {
        return (String) get(70);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.TRANSMISI</code>.
     */
    public void setTransmisi(String value) {
        set(71, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.TRANSMISI</code>.
     */
    public String getTransmisi() {
        return (String) get(71);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.TRANSMISICAT</code>.
     */
    public void setTransmisicat(String value) {
        set(72, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.TRANSMISICAT</code>.
     */
    public String getTransmisicat() {
        return (String) get(72);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.SEWATRANSMISI</code>.
     */
    public void setSewatransmisi(String value) {
        set(73, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.SEWATRANSMISI</code>.
     */
    public String getSewatransmisi() {
        return (String) get(73);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.SEWABWTOTAL</code>.
     */
    public void setSewabwtotal(String value) {
        set(74, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.SEWABWTOTAL</code>.
     */
    public String getSewabwtotal() {
        return (String) get(74);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.SEWABWDOWN</code>.
     */
    public void setSewabwdown(String value) {
        set(75, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.SEWABWDOWN</code>.
     */
    public String getSewabwdown() {
        return (String) get(75);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.SEWABWUP</code>.
     */
    public void setSewabwup(String value) {
        set(76, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.SEWABWUP</code>.
     */
    public String getSewabwup() {
        return (String) get(76);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.VENDORLC</code>.
     */
    public void setVendorlc(String value) {
        set(77, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.VENDORLC</code>.
     */
    public String getVendorlc() {
        return (String) get(77);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.VENDORVSAT</code>.
     */
    public void setVendorvsat(String value) {
        set(78, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.VENDORVSAT</code>.
     */
    public String getVendorvsat() {
        return (String) get(78);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.HEIGHTTOWER</code>.
     */
    public void setHeighttower(String value) {
        set(79, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.HEIGHTTOWER</code>.
     */
    public String getHeighttower() {
        return (String) get(79);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.HEIGHTANTENNA</code>.
     */
    public void setHeightantenna(String value) {
        set(80, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.HEIGHTANTENNA</code>.
     */
    public String getHeightantenna() {
        return (String) get(80);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.AZIMUTH</code>.
     */
    public void setAzimuth(String value) {
        set(81, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.AZIMUTH</code>.
     */
    public String getAzimuth() {
        return (String) get(81);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.BANDTYPE</code>.
     */
    public void setBandtype(String value) {
        set(82, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.BANDTYPE</code>.
     */
    public String getBandtype() {
        return (String) get(82);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.MTILT</code>.
     */
    public void setMtilt(String value) {
        set(83, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.MTILT</code>.
     */
    public String getMtilt() {
        return (String) get(83);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.ETILT</code>.
     */
    public void setEtilt(String value) {
        set(84, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.ETILT</code>.
     */
    public String getEtilt() {
        return (String) get(84);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.NAMADESABAKTI</code>.
     */
    public void setNamadesabakti(String value) {
        set(85, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.NAMADESABAKTI</code>.
     */
    public String getNamadesabakti() {
        return (String) get(85);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.SITEIDBAKTI</code>.
     */
    public void setSiteidbakti(String value) {
        set(86, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.SITEIDBAKTI</code>.
     */
    public String getSiteidbakti() {
        return (String) get(86);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.LATBAKTI</code>.
     */
    public void setLatbakti(String value) {
        set(87, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.LATBAKTI</code>.
     */
    public String getLatbakti() {
        return (String) get(87);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.LONGBAKTI</code>.
     */
    public void setLongbakti(String value) {
        set(88, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.LONGBAKTI</code>.
     */
    public String getLongbakti() {
        return (String) get(88);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.PROJECTPHASE</code>.
     */
    public void setProjectphase(String value) {
        set(89, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.PROJECTPHASE</code>.
     */
    public String getProjectphase() {
        return (String) get(89);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.TGLMODERNISASI</code>.
     */
    public void setTglmodernisasi(String value) {
        set(90, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.TGLMODERNISASI</code>.
     */
    public String getTglmodernisasi() {
        return (String) get(90);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.TGL4GBATCHMODERN</code>.
     */
    public void setTgl4gbatchmodern(String value) {
        set(91, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.TGL4GBATCHMODERN</code>.
     */
    public String getTgl4gbatchmodern() {
        return (String) get(91);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.TGL4GBATCH343</code>.
     */
    public void setTgl4gbatch343(String value) {
        set(92, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.TGL4GBATCH343</code>.
     */
    public String getTgl4gbatch343() {
        return (String) get(92);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.TGLMPTERRESTRIAL</code>.
     */
    public void setTglmpterrestrial(String value) {
        set(93, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.TGLMPTERRESTRIAL</code>.
     */
    public String getTglmpterrestrial() {
        return (String) get(93);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.col94</code>.
     */
    public void setCol94(String value) {
        set(94, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.col94</code>.
     */
    public String getCol94() {
        return (String) get(94);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.col95</code>.
     */
    public void setCol95(String value) {
        set(95, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.col95</code>.
     */
    public String getCol95() {
        return (String) get(95);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.col96</code>.
     */
    public void setCol96(String value) {
        set(96, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.col96</code>.
     */
    public String getCol96() {
        return (String) get(96);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.col97</code>.
     */
    public void setCol97(String value) {
        set(97, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.col97</code>.
     */
    public String getCol97() {
        return (String) get(97);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.col98</code>.
     */
    public void setCol98(String value) {
        set(98, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.col98</code>.
     */
    public String getCol98() {
        return (String) get(98);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.col99</code>.
     */
    public void setCol99(String value) {
        set(99, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.col99</code>.
     */
    public String getCol99() {
        return (String) get(99);
    }

    /**
     * Setter for <code>chrono.temp_crstatic.col100</code>.
     */
    public void setCol100(String value) {
        set(100, value);
    }

    /**
     * Getter for <code>chrono.temp_crstatic.col100</code>.
     */
    public String getCol100() {
        return (String) get(100);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TempCrstaticRecord
     */
    public TempCrstaticRecord() {
        super(TempCrstatic.TEMP_CRSTATIC);
    }

    /**
     * Create a detached, initialised TempCrstaticRecord
     */
    public TempCrstaticRecord(Integer id_, String status, String cell, String site, String ne, String ne2g, String ne4g, String siteid, String neid, String sitename, String cellname, String desa, String kecamatan, String kabupaten, String provinsi, String latdrm, String longdrm, String latdt, String longdt, String lat, String long_, String regional, String area, String neigbourcountry, String sitetype, String project, String klasifikasiproject, String projecttracking, String tglconnected, String tgloa, String technologycolo, String network, String band, String btssector, String trxcell, String lac, String cellid, String lacci, String bscname, String bscspc, String rac, String mssspc, String mgwname, String mssname, String sgsn, String tal, String tac, String pci, String ulfreq, String dlfreq, String mme, String sgw, String tariffzone, String typename, String btssdr, String btstype, String btscat, String btsvendor, String antennatype, String antennacat, String sewaantenna, String antennavendor, String towertype, String towercategory, String sewatower, String towervendor, String powertype, String powersummary, String powercategory, String sewapower, String powervendor, String transmisi, String transmisicat, String sewatransmisi, String sewabwtotal, String sewabwdown, String sewabwup, String vendorlc, String vendorvsat, String heighttower, String heightantenna, String azimuth, String bandtype, String mtilt, String etilt, String namadesabakti, String siteidbakti, String latbakti, String longbakti, String projectphase, String tglmodernisasi, String tgl4gbatchmodern, String tgl4gbatch343, String tglmpterrestrial, String col94, String col95, String col96, String col97, String col98, String col99, String col100) {
        super(TempCrstatic.TEMP_CRSTATIC);

        set(0, id_);
        set(1, status);
        set(2, cell);
        set(3, site);
        set(4, ne);
        set(5, ne2g);
        set(6, ne4g);
        set(7, siteid);
        set(8, neid);
        set(9, sitename);
        set(10, cellname);
        set(11, desa);
        set(12, kecamatan);
        set(13, kabupaten);
        set(14, provinsi);
        set(15, latdrm);
        set(16, longdrm);
        set(17, latdt);
        set(18, longdt);
        set(19, lat);
        set(20, long_);
        set(21, regional);
        set(22, area);
        set(23, neigbourcountry);
        set(24, sitetype);
        set(25, project);
        set(26, klasifikasiproject);
        set(27, projecttracking);
        set(28, tglconnected);
        set(29, tgloa);
        set(30, technologycolo);
        set(31, network);
        set(32, band);
        set(33, btssector);
        set(34, trxcell);
        set(35, lac);
        set(36, cellid);
        set(37, lacci);
        set(38, bscname);
        set(39, bscspc);
        set(40, rac);
        set(41, mssspc);
        set(42, mgwname);
        set(43, mssname);
        set(44, sgsn);
        set(45, tal);
        set(46, tac);
        set(47, pci);
        set(48, ulfreq);
        set(49, dlfreq);
        set(50, mme);
        set(51, sgw);
        set(52, tariffzone);
        set(53, typename);
        set(54, btssdr);
        set(55, btstype);
        set(56, btscat);
        set(57, btsvendor);
        set(58, antennatype);
        set(59, antennacat);
        set(60, sewaantenna);
        set(61, antennavendor);
        set(62, towertype);
        set(63, towercategory);
        set(64, sewatower);
        set(65, towervendor);
        set(66, powertype);
        set(67, powersummary);
        set(68, powercategory);
        set(69, sewapower);
        set(70, powervendor);
        set(71, transmisi);
        set(72, transmisicat);
        set(73, sewatransmisi);
        set(74, sewabwtotal);
        set(75, sewabwdown);
        set(76, sewabwup);
        set(77, vendorlc);
        set(78, vendorvsat);
        set(79, heighttower);
        set(80, heightantenna);
        set(81, azimuth);
        set(82, bandtype);
        set(83, mtilt);
        set(84, etilt);
        set(85, namadesabakti);
        set(86, siteidbakti);
        set(87, latbakti);
        set(88, longbakti);
        set(89, projectphase);
        set(90, tglmodernisasi);
        set(91, tgl4gbatchmodern);
        set(92, tgl4gbatch343);
        set(93, tglmpterrestrial);
        set(94, col94);
        set(95, col95);
        set(96, col96);
        set(97, col97);
        set(98, col98);
        set(99, col99);
        set(100, col100);
    }
}
