/*
 * This file is generated by jOOQ.
*/
package id.mit.chrono.server.model.tables.records;


import id.mit.chrono.server.model.tables.Ztegcellrellcell;

import javax.annotation.Generated;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ZtegcellrellcellRecord extends UpdatableRecordImpl<ZtegcellrellcellRecord> {

    private static final long serialVersionUID = 618073506;

    /**
     * Setter for <code>chrono.ztegcellrellcell.ztegcellrellcell_id</code>.
     */
    public void setZtegcellrellcellId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.ztegcellrellcell_id</code>.
     */
    public ULong getZtegcellrellcellId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.ztegcellrellcell_crcollectortaskfiles</code>.
     */
    public void setZtegcellrellcellCrcollectortaskfiles(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.ztegcellrellcell_crcollectortaskfiles</code>.
     */
    public ULong getZtegcellrellcellCrcollectortaskfiles() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.ztegcellrellcell_date</code>.
     */
    public void setZtegcellrellcellDate(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.ztegcellrellcell_date</code>.
     */
    public UInteger getZtegcellrellcellDate() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.ztegcellrellcell_datefrom</code>.
     */
    public void setZtegcellrellcellDatefrom(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.ztegcellrellcell_datefrom</code>.
     */
    public UInteger getZtegcellrellcellDatefrom() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.ztegcellrellcell_ztebsc</code>.
     */
    public void setZtegcellrellcellZtebsc(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.ztegcellrellcell_ztebsc</code>.
     */
    public ULong getZtegcellrellcellZtebsc() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.ztegcellrellcell_ztebts</code>.
     */
    public void setZtegcellrellcellZtebts(ULong value) {
        set(5, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.ztegcellrellcell_ztebts</code>.
     */
    public ULong getZtegcellrellcellZtebts() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.ztegcellrellcell_ztegcell</code>.
     */
    public void setZtegcellrellcellZtegcell(ULong value) {
        set(6, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.ztegcellrellcell_ztegcell</code>.
     */
    public ULong getZtegcellrellcellZtegcell() {
        return (ULong) get(6);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.MOI</code>.
     */
    public void setMoi(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.MOI</code>.
     */
    public String getMoi() {
        return (String) get(7);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.SubNetwork</code>.
     */
    public void setSubnetwork(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.SubNetwork</code>.
     */
    public String getSubnetwork() {
        return (String) get(8);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.MEID</code>.
     */
    public void setMeid(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.MEID</code>.
     */
    public String getMeid() {
        return (String) get(9);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.GBssFunction</code>.
     */
    public void setGbssfunction(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.GBssFunction</code>.
     */
    public String getGbssfunction() {
        return (String) get(10);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.GBtsSiteManager</code>.
     */
    public void setGbtssitemanager(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.GBtsSiteManager</code>.
     */
    public String getGbtssitemanager() {
        return (String) get(11);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.GGsmCell</code>.
     */
    public void setGgsmcell(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.GGsmCell</code>.
     */
    public String getGgsmcell() {
        return (String) get(12);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.GEutranRelation</code>.
     */
    public void setGeutranrelation(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.GEutranRelation</code>.
     */
    public String getGeutranrelation() {
        return (String) get(13);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.userLabel</code>.
     */
    public void setUserlabel(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.userLabel</code>.
     */
    public String getUserlabel() {
        return (String) get(14);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.refGExternalEutranCellFDD</code>.
     */
    public void setRefgexternaleutrancellfdd(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.refGExternalEutranCellFDD</code>.
     */
    public String getRefgexternaleutrancellfdd() {
        return (String) get(15);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.refGExternalEutranCellTDD</code>.
     */
    public void setRefgexternaleutrancelltdd(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.refGExternalEutranCellTDD</code>.
     */
    public String getRefgexternaleutrancelltdd() {
        return (String) get(16);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.GEutranRelationSeq</code>.
     */
    public void setGeutranrelationseq(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.GEutranRelationSeq</code>.
     */
    public String getGeutranrelationseq() {
        return (String) get(17);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.arfcnLtePrio</code>.
     */
    public void setArfcnlteprio(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.arfcnLtePrio</code>.
     */
    public String getArfcnlteprio() {
        return (String) get(18);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.ncelBlackListInd</code>.
     */
    public void setNcelblacklistind(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.ncelBlackListInd</code>.
     */
    public String getNcelblacklistind() {
        return (String) get(19);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.ArfcnLTEPrio_T</code>.
     */
    public void setArfcnlteprioT(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.ArfcnLTEPrio_T</code>.
     */
    public String getArfcnlteprioT() {
        return (String) get(20);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.ArfcnLTEPrioFR</code>.
     */
    public void setArfcnltepriofr(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.ArfcnLTEPrioFR</code>.
     */
    public String getArfcnltepriofr() {
        return (String) get(21);
    }

    /**
     * Setter for <code>chrono.ztegcellrellcell.OnlyForFR</code>.
     */
    public void setOnlyforfr(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>chrono.ztegcellrellcell.OnlyForFR</code>.
     */
    public String getOnlyforfr() {
        return (String) get(22);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<ULong, ULong> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ZtegcellrellcellRecord
     */
    public ZtegcellrellcellRecord() {
        super(Ztegcellrellcell.ZTEGCELLRELLCELL);
    }

    /**
     * Create a detached, initialised ZtegcellrellcellRecord
     */
    public ZtegcellrellcellRecord(ULong ztegcellrellcellId, ULong ztegcellrellcellCrcollectortaskfiles, UInteger ztegcellrellcellDate, UInteger ztegcellrellcellDatefrom, ULong ztegcellrellcellZtebsc, ULong ztegcellrellcellZtebts, ULong ztegcellrellcellZtegcell, String moi, String subnetwork, String meid, String gbssfunction, String gbtssitemanager, String ggsmcell, String geutranrelation, String userlabel, String refgexternaleutrancellfdd, String refgexternaleutrancelltdd, String geutranrelationseq, String arfcnlteprio, String ncelblacklistind, String arfcnlteprioT, String arfcnltepriofr, String onlyforfr) {
        super(Ztegcellrellcell.ZTEGCELLRELLCELL);

        set(0, ztegcellrellcellId);
        set(1, ztegcellrellcellCrcollectortaskfiles);
        set(2, ztegcellrellcellDate);
        set(3, ztegcellrellcellDatefrom);
        set(4, ztegcellrellcellZtebsc);
        set(5, ztegcellrellcellZtebts);
        set(6, ztegcellrellcellZtegcell);
        set(7, moi);
        set(8, subnetwork);
        set(9, meid);
        set(10, gbssfunction);
        set(11, gbtssitemanager);
        set(12, ggsmcell);
        set(13, geutranrelation);
        set(14, userlabel);
        set(15, refgexternaleutrancellfdd);
        set(16, refgexternaleutrancelltdd);
        set(17, geutranrelationseq);
        set(18, arfcnlteprio);
        set(19, ncelblacklistind);
        set(20, arfcnlteprioT);
        set(21, arfcnltepriofr);
        set(22, onlyforfr);
    }
}
